/* ============================================================
   ESCAPE THE VIVA - Questions Bank (60 Questions)
   ============================================================ */

const allQuestions = [
  // ========== OOP ==========
  { topic:'OOP', difficulty:'easy',
    question:'What does OOP stand for?',
    options:['Object Oriented Programming','Only One Program','Order of Pizza Pls',"I don't know sir"],
    correct:0, hint:'Think about the "O" - it relates to real-world things like cars and animals.',
    professorAsk:'What does OOP stand for?',
    correctReaction:'Good! At least you know something. 👍',
    wrongReaction:'Order of Pizza?? Are you in a hotel or college? 😤',
    wrongComment:'This is why students are failing these days!' },

  { topic:'OOP', difficulty:'easy',
    question:'What is Encapsulation in OOP?',
    options:['Hiding data and methods inside a class','Putting code in capsules','A medicine term','Wrapping gifts nicely'],
    correct:0, hint:'Think of a capsule that hides what is inside it.',
    professorAsk:'Tell me about Encapsulation!',
    correctReaction:'Correct! Data hiding! You studied! 👏',
    wrongReaction:'Putting code in capsules?! Which pharmacy taught you? 😡',
    wrongComment:'Encapsulation is DAY ONE topic!' },

  { topic:'OOP', difficulty:'easy',
    question:'What is Inheritance in OOP?',
    options:['Child class gets parent class properties','Getting money from parents','Copying homework','None of the above'],
    correct:0, hint:'Think parent and child - what does a child get from parents?',
    professorAsk:'Explain Inheritance!',
    correctReaction:"Yes! Parent to child! Not your dad's money though! 😄",
    wrongReaction:'Getting money from parents?! Wrong subject entirely! 😤',
    wrongComment:'Inheritance = Child class extending Parent class!' },

  { topic:'OOP', difficulty:'medium',
    question:'What is Polymorphism?',
    options:['One interface, many forms','Many professors, one student','A shape-shifting animal','Greek food item'],
    correct:0, hint:'Poly = many, morph = form/shape.',
    professorAsk:'Define Polymorphism!',
    correctReaction:'Poly=many, morph=forms! Excellent! 🌟',
    wrongReaction:'Greek food?! This is Computer Science not a restaurant! 🤬',
    wrongComment:'POLY-MOR-PHISM! Repeat after me!' },

  { topic:'OOP', difficulty:'medium',
    question:'What is an Abstract Class?',
    options:['A class that cannot be instantiated directly','A class that is confusing','An art class','Class with no students'],
    correct:0, hint:'You cannot create an object directly from this type of class.',
    professorAsk:'What is an Abstract Class?',
    correctReaction:'Cannot be instantiated directly! Perfect! 💯',
    wrongReaction:'An art class?! Wrong department sir! 😤',
    wrongComment:'Abstract = incomplete blueprint you cannot build directly!' },

  { topic:'OOP', difficulty:'medium',
    question:'What is method overloading?',
    options:['Same method name with different parameters','A method working too hard','Overloading the CPU','Too many methods in a class'],
    correct:0, hint:'Same name, different signature - parameters differ.',
    professorAsk:'Explain method overloading!',
    correctReaction:'Same name, different signature! Correct! 👍',
    wrongReaction:'Method working too hard?! Like you should be doing! 😡',
    wrongComment:'Overloading = compile time polymorphism!' },

  { topic:'OOP', difficulty:'hard',
    question:'Which SOLID principle states a class should have only one reason to change?',
    options:['Single Responsibility Principle','Open Closed Principle','Change Management Principle','Professor Said So Principle'],
    correct:0, hint:'S in SOLID - Single something...',
    professorAsk:'Which SOLID principle limits class responsibility?',
    correctReaction:'SRP! Solid answer! Pun intended! 🎯',
    wrongReaction:'Professor Said So?! I say ZERO MARKS! 😡',
    wrongComment:'S in SOLID = Single Responsibility Principle!' },

  { topic:'OOP', difficulty:'hard',
    question:'What is the difference between method overloading and overriding?',
    options:['Overloading is compile-time, overriding is runtime polymorphism','They are the same thing','Overriding uses same parameters','Overloading only works in Java'],
    correct:0, hint:'One happens at compile time, one at runtime.',
    professorAsk:'Overloading vs Overriding - difference?',
    correctReaction:'Compile vs Runtime polymorphism! Expert! 🏆',
    wrongReaction:'They are same?! They are COMPLETELY different! 😡',
    wrongComment:'Overloading=compile time, Overriding=runtime!' },

  // ========== JAVA ==========
  { topic:'Java', difficulty:'easy',
    question:"What does the 'this' keyword refer to in Java?",
    options:['The current object instance','The previous year syllabus','This college only','I am not sure sir'],
    correct:0, hint:'It refers to the object that is currently being used.',
    professorAsk:"Explain 'this' keyword in Java!",
    correctReaction:'Refers to current object! Correct! 🎯',
    wrongReaction:"Refers to previous year?! What kind of answer is THIS?! 😡",
    wrongComment:'THIS keyword = THIS current object! Simple!' },

  { topic:'Java', difficulty:'medium',
    question:"What is the output of System.out.println(1 + 2 + '3')?",
    options:['33','6','123','Compilation Error'],
    correct:0, hint:'1+2 first (int), then result + char 3.',
    professorAsk:"Quick! Output of: System.out.println(1 + 2 + '3')?",
    correctReaction:'33! You understand type coercion! 🏆',
    wrongReaction:'WRONG! Java arithmetic is not forgiving! 😡',
    wrongComment:"1+2=3 (int), 3+'3'=33 (char addition)! Basics!" },

  { topic:'Java', difficulty:'easy',
    question:'What does JVM stand for?',
    options:['Java Virtual Machine','Java Very Much Sir','Just Virtual Memory','Java Viva Machine'],
    correct:0, hint:'It is the engine that runs Java programs.',
    professorAsk:'What is JVM?',
    correctReaction:'Java Virtual Machine! Well done! ☕',
    wrongReaction:'Java Viva Machine?! Are you mocking me?! 😤',
    wrongComment:'JVM = Java Virtual Machine! Makes Java portable!' },

  { topic:'Java', difficulty:'medium',
    question:'What is the difference between == and .equals() in Java?',
    options:['== checks reference, .equals() checks value','They are exactly the same','== is faster always','equals() is only for Strings'],
    correct:0, hint:'One checks memory address, one checks actual content.',
    professorAsk:'== vs .equals() in Java?',
    correctReaction:'Reference vs Value comparison! You studied! 🌟',
    wrongReaction:'They are same?! They are absolutely NOT same! 😡',
    wrongComment:'== checks if same object, equals() checks same content!' },

  { topic:'Java', difficulty:'easy',
    question:'What is a constructor in Java?',
    options:['A method that initializes an object','A person who builds things','An alternative to main method','A special type of loop'],
    correct:0, hint:'It runs automatically when you create a new object.',
    professorAsk:'What is a constructor?',
    correctReaction:'Initializes the object! Perfect! 🏗️',
    wrongReaction:'A person who builds things?! Civil engineering is next door! 😤',
    wrongComment:'Constructor = same name as class, no return type!' },

  { topic:'Java', difficulty:'medium',
    question:'What does the final keyword do in Java?',
    options:['Prevents further modification','Marks last line of code','Ends the program execution','It is a final exam keyword'],
    correct:0, hint:'Final means it cannot be changed after assignment.',
    professorAsk:'What does the final keyword do?',
    correctReaction:'Prevents modification! Locks it down! 🔒',
    wrongReaction:'Final exam keyword?! IS THIS A COMEDY SHOW?! 😡',
    wrongComment:'final variable=constant, final method=no override, final class=no extend!' },

  { topic:'Java', difficulty:'hard',
    question:'What is the difference between ArrayList and LinkedList in Java?',
    options:['ArrayList uses array, LinkedList uses nodes - different access speeds','They are completely identical','LinkedList is faster always','ArrayList uses more memory always'],
    correct:0, hint:'Think about how data is stored and how fast you can access it.',
    professorAsk:'ArrayList vs LinkedList - go!',
    correctReaction:'Array vs Node structure! Access vs Insert speed! Expert! 🌟',
    wrongReaction:'Completely identical?! Then why do both exist?! 😡',
    wrongComment:'ArrayList=O(1) access, LinkedList=O(1) insert/delete at ends!' },

  // ========== DSA ==========
  { topic:'DSA', difficulty:'easy',
    question:'What is the time complexity of binary search?',
    options:['O(log n)','O(n)','O(n log n)','O(1)'],
    correct:0, hint:'The array is halved each time you search.',
    professorAsk:'Time complexity of binary search?',
    correctReaction:'O(log n)! Halving each step! Perfect! 📊',
    wrongReaction:'O(n)?! That is LINEAR search! Different thing! 😡',
    wrongComment:'Binary search HALVES the search space each time!' },

  { topic:'DSA', difficulty:'easy',
    question:'Which data structure uses the LIFO principle?',
    options:['Stack','Queue','LinkedList','My dying brain cells'],
    correct:0, hint:'Think of a stack of plates - you take from the top.',
    professorAsk:'Which data structure follows LIFO?',
    correctReaction:'Stack! Last In First Out! Correct! 📚',
    wrongReaction:'Your brain cells?! LIFO of your grades too! 😤',
    wrongComment:'Stack=LIFO (Last In First Out), Queue=FIFO!' },

  { topic:'DSA', difficulty:'medium',
    question:'What is the worst case time complexity of QuickSort?',
    options:['O(n²)','O(n log n)','O(log n)','O(n)'],
    correct:0, hint:'Happens when pivot is always the smallest or largest element.',
    professorAsk:'Worst case time complexity of QuickSort?',
    correctReaction:'O(n²) when pivot is always min/max! Correct! 🎯',
    wrongReaction:'O(n log n) is the AVERAGE case, not worst! 😡',
    wrongComment:'QuickSort worst case: sorted array with bad pivot choice!' },

  { topic:'DSA', difficulty:'easy',
    question:'What is the primary use of a Hash Table?',
    options:['Fast key-value pair lookup in O(1)','Only for hashing passwords','Creating HTML tables faster','Organizing breakfast items'],
    correct:0, hint:'Average case lookup is constant time.',
    professorAsk:'What is Hash Table used for?',
    correctReaction:'O(1) average lookup! Brilliant answer! 🔑',
    wrongReaction:'Organizing breakfast?! GET OUT OF MY VIVA ROOM! 😡',
    wrongComment:'Hash Table = O(1) average for search, insert, delete!' },

  { topic:'DSA', difficulty:'medium',
    question:'What property does a Binary Search Tree (BST) maintain?',
    options:['Left child < Parent < Right child','Right child < Parent < Left child','Random order throughout','Only alphabetical ordering'],
    correct:0, hint:'Values on the left are smaller, values on right are larger.',
    professorAsk:'What is the BST property?',
    correctReaction:'Left smaller, right larger! Perfect BST knowledge! 🌳',
    wrongReaction:'Random order?! Then it is just a regular tree! 😤',
    wrongComment:'BST: Left subtree < Root < Right subtree! Always!' },

  { topic:'DSA', difficulty:'hard',
    question:'What is the time complexity of Dijkstra\'s algorithm with a min-heap?',
    options:['O((V + E) log V)','O(V²)','O(E log V)','O(V log E)'],
    correct:0, hint:'V = vertices, E = edges. The heap helps reduce complexity.',
    professorAsk:'Dijkstra\'s complexity with min-heap?',
    correctReaction:'O((V+E) log V)! Algorithm master! 🏆',
    wrongReaction:'O(V²) is basic Dijkstra without heap! 😡',
    wrongComment:'With min-heap: O((V+E)logV). Without: O(V²)!' },

  // ========== DBMS ==========
  { topic:'DBMS', difficulty:'easy',
    question:'What does SQL stand for?',
    options:['Structured Query Language','Simple Question Language','Some Query Lagta Hai Sir','Student Question Loop'],
    correct:0, hint:'It is a language used to communicate with databases.',
    professorAsk:'What does SQL stand for?',
    correctReaction:'Structured Query Language! Correct! 🗄️',
    wrongReaction:'Some Query Lagta Hai?! WHAT IS THIS ANSWER?! 😡',
    wrongComment:'SQL = Structured Query Language! Industry standard!' },

  { topic:'DBMS', difficulty:'easy',
    question:'What is a Primary Key in a database?',
    options:['A unique identifier for each record in a table','The most important key on your keyboard','Always the first column in a table','The password to access the database'],
    correct:0, hint:'It uniquely identifies each row and cannot be null.',
    professorAsk:'Define a Primary Key!',
    correctReaction:'Uniquely identifies each row! Perfect! 🔑',
    wrongReaction:'Password to database?! That is not even close! 😤',
    wrongComment:'Primary Key = Unique + NOT NULL! Always!' },

  { topic:'DBMS', difficulty:'medium',
    question:'What is database normalization?',
    options:['Process of organizing data to reduce redundancy','Making all data look normal','Formatting the entire database','Creating a backup of the database'],
    correct:0, hint:'Think about eliminating repeated data.',
    professorAsk:'What is database normalization?',
    correctReaction:'Reduce redundancy, improve integrity! 🌟',
    wrongReaction:'Making data look normal?! WHAT is abnormal data?! 😡',
    wrongComment:'Normalization: 1NF, 2NF, 3NF, BCNF! Eliminate redundancy!' },

  { topic:'DBMS', difficulty:'medium',
    question:'What does ACID stand for in database transactions?',
    options:['Atomicity, Consistency, Isolation, Durability','A Chemical In the Database','Automated Computer Identification','All Correct Information Done'],
    correct:0, hint:'These are four properties that guarantee reliable transactions.',
    professorAsk:'What is ACID in database transactions?',
    correctReaction:'ACID properties! Transaction reliability expert! 💯',
    wrongReaction:'A Chemical In Database?! Call the chemistry department! 😡',
    wrongComment:'ACID: Atomicity, Consistency, Isolation, Durability!' },

  { topic:'DBMS', difficulty:'easy',
    question:'What is a Foreign Key?',
    options:['A key that references the Primary Key of another table','A key imported from another country','A secondary password for the database','A backup key for emergencies'],
    correct:0, hint:'It creates a link between two tables.',
    professorAsk:'What is a Foreign Key?',
    correctReaction:'Links tables together! Relational genius! 🔗',
    wrongReaction:'A key from another country?! DEPORTATION OF YOUR MARKS! 😤',
    wrongComment:'Foreign Key = creates relationship between tables!' },

  { topic:'DBMS', difficulty:'hard',
    question:'What is the difference between INNER JOIN and LEFT JOIN?',
    options:['INNER JOIN returns matching rows only, LEFT JOIN returns all left rows','They return the same results','LEFT JOIN is faster always','INNER JOIN returns all rows from both'],
    correct:0, hint:'Think about which rows are kept when there is no match.',
    professorAsk:'INNER JOIN vs LEFT JOIN - explain!',
    correctReaction:'Matching vs All-left rows! Database master! 🏆',
    wrongReaction:'Same results?! Run both queries and look! 😡',
    wrongComment:'INNER=only matches, LEFT=all left + matches, null for no match!' },

  // ========== OS ==========
  { topic:'OS', difficulty:'medium',
    question:'What is a deadlock in Operating Systems?',
    options:['When two or more processes wait for each other indefinitely','When the computer suddenly dies','When sir locks the exam room door','System requires a restart to continue'],
    correct:0, hint:'Think of two processes each waiting for a resource the other holds.',
    professorAsk:'What is a deadlock in OS?',
    correctReaction:'Circular waiting! You actually read the textbook! 😲',
    wrongReaction:'Sir locks the door?! This is not a Bollywood film! 😡',
    wrongComment:'Deadlock conditions: Mutual exclusion + Hold & Wait + No preemption + Circular wait!' },

  { topic:'OS', difficulty:'medium',
    question:'What is Virtual Memory?',
    options:['Using disk storage as an extension of RAM','Memory that is completely fake','RAM used only in video games','A backup copy of RAM data'],
    correct:0, hint:'It allows programs to use more memory than physically available.',
    professorAsk:'Explain Virtual Memory!',
    correctReaction:'Disk extends RAM capacity! Perfect understanding! 💾',
    wrongReaction:'Fake memory?! YOUR knowledge is what is fake! 😤',
    wrongComment:'Virtual Memory = swap space on disk used as RAM extension!' },

  { topic:'OS', difficulty:'easy',
    question:'What is the role of the OS Scheduler?',
    options:['Decides which process gets CPU time and when','Schedules professor-student meetings','Creates the university timetable','Functions as an alarm clock'],
    correct:0, hint:'It manages which program runs on the processor.',
    professorAsk:'What does the OS Scheduler do?',
    correctReaction:'CPU process allocation! You understand OS! 🖥️',
    wrongReaction:'Schedules my meetings?! I schedule YOUR failure! 😡',
    wrongComment:'Scheduler = decides CPU allocation among competing processes!' },

  { topic:'OS', difficulty:'hard',
    question:'What is the difference between process and thread?',
    options:['Process is independent with own memory, thread shares process memory','They are exactly the same','Thread uses more memory than process','Process is faster than thread'],
    correct:0, hint:'One is heavyweight and isolated, the other is lightweight and shared.',
    professorAsk:'Process vs Thread - what is the difference?',
    correctReaction:'Independent vs shared memory! OS expert! 🌟',
    wrongReaction:'Exactly same?! Then why are they taught separately?! 😡',
    wrongComment:'Process=isolated memory space, Thread=shares parent process memory!' },

  // ========== CN ==========
  { topic:'CN', difficulty:'easy',
    question:'What does HTTP stand for?',
    options:['HyperText Transfer Protocol','High Technology Transfer Program','How To Transfer Pages','HyperText Transfer Permission'],
    correct:0, hint:'It is the foundation protocol of the World Wide Web.',
    professorAsk:'What does HTTP stand for?',
    correctReaction:'HyperText Transfer Protocol! Web foundation! 🌐',
    wrongReaction:'How To Transfer Pages?! Please Google it after this! 😡',
    wrongComment:'HTTP = HyperText Transfer Protocol! Web runs on this!' },

  { topic:'CN', difficulty:'medium',
    question:'How many layers does the OSI model have?',
    options:['7 layers from Physical to Application','5 layers total','3 layers only','It depends on the network'],
    correct:0, hint:'Please All People Seem To Need Data Processing.',
    professorAsk:'How many layers in the OSI model?',
    correctReaction:'7 layers! Physical to Application! Complete! 📡',
    wrongReaction:'5 layers?! That is TCP/IP model! Different! 😤',
    wrongComment:'OSI has 7: Physical, Data Link, Network, Transport, Session, Presentation, Application!' },

  { topic:'CN', difficulty:'medium',
    question:'What is the key difference between TCP and UDP?',
    options:['TCP is reliable with handshake, UDP is fast without guarantee','TCP is always faster than UDP','They work identically under the hood','UDP was created after TCP to improve it'],
    correct:0, hint:'One guarantees delivery, the other sacrifices reliability for speed.',
    professorAsk:'TCP vs UDP - main difference?',
    correctReaction:'Reliable vs Fast! Connection vs Connectionless! 🌐',
    wrongReaction:'Identically?! They are completely different protocols! 😡',
    wrongComment:'TCP=3-way handshake+reliable, UDP=fire and forget, faster!' },

  { topic:'CN', difficulty:'easy',
    question:'What is an IP address?',
    options:['A unique numerical identifier assigned to each device on a network','Your Internet Password','Intellectual Property address','Indian Protocol number'],
    correct:0, hint:'Every device connected to a network needs one of these.',
    professorAsk:'What is an IP address?',
    correctReaction:'Unique network identifier! Every device needs one! 📍',
    wrongReaction:'Internet Password?! Your exam marks are now passworded to ZERO! 😡',
    wrongComment:'IP = Internet Protocol address, uniquely identifies network devices!' },

  { topic:'CN', difficulty:'hard',
    question:'What is the purpose of DNS?',
    options:['Translates domain names to IP addresses','Domain Name Storage server','Distributes Network Security','Dynamic Node System'],
    correct:0, hint:'It is like a phone book for the internet.',
    professorAsk:'What does DNS do?',
    correctReaction:'Domain to IP translation! Internet phonebook! 🌐',
    wrongReaction:'Network Security?! That is a firewall! 😡',
    wrongComment:'DNS = Domain Name System, translates google.com to 142.250.x.x!' },

  // ========== Math/Theory ==========
  { topic:'Math', difficulty:'easy',
    question:'What is the derivative of sin(x)?',
    options:['cos(x)','-cos(x)','sin(x)','tan(x)'],
    correct:0, hint:'Differentiate trigonometric functions - first one in the cycle.',
    professorAsk:'What is the derivative of sin(x)?',
    correctReaction:'cos(x)! Calculus champion! 📐',
    wrongReaction:'-cos(x)?! You mixed up differentiation with integration! 😡',
    wrongComment:'d/dx(sin x) = cos x! This was Class 12 syllabus!' },

  { topic:'Math', difficulty:'easy',
    question:'What does Big O notation primarily measure?',
    options:['The efficiency and scalability of an algorithm','A specific music note in coding','The circumference of a circle','Operational overhead of software'],
    correct:0, hint:'It describes how runtime grows as input size grows.',
    professorAsk:'What is Big O notation used for?',
    correctReaction:'Algorithm complexity analysis! Perfect understanding! 📊',
    wrongReaction:'A music note?! This is CS not the music school! 😤',
    wrongComment:'Big O = worst-case time or space complexity of an algorithm!' },

  { topic:'Math', difficulty:'medium',
    question:'What is the result of 2^10?',
    options:['1024','512','2048','1000'],
    correct:0, hint:'2 to the power of 10 - a common value in computing.',
    professorAsk:'Quick math! What is 2 to the power of 10?',
    correctReaction:'1024! Binary mathematics master! 💻',
    wrongReaction:'512?! That is 2^9! Off by one! 😡',
    wrongComment:'2^10 = 1024! Common in memory (KB, MB, GB)!' },

  // ========== General CS ==========
  { topic:'CS', difficulty:'easy',
    question:'What is recursion in programming?',
    options:['A function that calls itself with a base case','Repeating the same lecture twice','Going back to first principles','A loop that has no termination condition'],
    correct:0, hint:'The function calls itself - but always needs a stopping condition.',
    professorAsk:'Define recursion!',
    correctReaction:'Function calls itself with a base case! 🔄',
    wrongReaction:'Repeating lectures?! Like I am forced to do now?! 😡',
    wrongComment:'To understand recursion, you must first understand recursion!' },

  { topic:'CS', difficulty:'easy',
    question:'What does a compiler do?',
    options:['Translates entire source code to machine code before execution','Automatically fixes all your code errors','Executes code one line at a time','A special type of processor chip'],
    correct:0, hint:'It converts the whole program at once, not line by line.',
    professorAsk:'What does a compiler do?',
    correctReaction:'Translates entire source to machine code! Correct! ⚙️',
    wrongReaction:'Fixes errors automatically?! I WISH it could fix yours! 😤',
    wrongComment:'Compiler=whole program translation. Interpreter=line by line!' },

  { topic:'CS', difficulty:'easy',
    question:'What is the fundamental difference between RAM and ROM?',
    options:['RAM is volatile (loses data), ROM is non-volatile (permanent)','RAM is always slower than ROM','RAM is read-only, ROM is writable','There is absolutely no difference'],
    correct:0, hint:'What happens to RAM data when you turn off the power?',
    professorAsk:'RAM vs ROM - fundamental difference?',
    correctReaction:'Volatile vs Non-volatile storage! Hardware expert! 💡',
    wrongReaction:'No difference?! 70 years of computing history disagrees! 😡',
    wrongComment:'RAM = loses data on power off. ROM = permanently stores data!' },

  { topic:'CS', difficulty:'easy',
    question:'What is an API?',
    options:['Application Programming Interface - allows software to communicate','A secret Programming Ingredient','Automated Program Input system','Annual Programming Index report'],
    correct:0, hint:'It defines how software components should interact with each other.',
    professorAsk:'What is an API?',
    correctReaction:'Interface between software components! Modern dev essential! 🔌',
    wrongReaction:'A secret ingredient?! We are building software not biryani! 😤',
    wrongComment:'API = contract/interface that allows applications to talk to each other!' },

  { topic:'CS', difficulty:'easy',
    question:'What is Git primarily used for?',
    options:['Version control - tracking changes in source code over time','Downloading files from the internet quickly','It is a programming language like Python','It is just an alternative to GitHub'],
    correct:0, hint:'It helps teams collaborate on code without overwriting each other.',
    professorAsk:'What is Git used for?',
    correctReaction:'Version control! Every professional developer uses Git! 📝',
    wrongReaction:'Downloading files?! That is a browser or wget! 😡',
    wrongComment:'Git tracks code history and enables team collaboration!' },

  { topic:'CS', difficulty:'easy',
    question:'What does CPU stand for?',
    options:['Central Processing Unit','Computer Personal Unit','Core Processing Utility chip','Central Program Updater'],
    correct:0, hint:'It is the brain of the computer that executes instructions.',
    professorAsk:'What does CPU stand for?',
    correctReaction:'Central Processing Unit! Brain of the computer! 🧠',
    wrongReaction:'Computer Personal Unit?! WHO taught you this?! Show me their name! 😤',
    wrongComment:'CPU = Central Processing Unit! The brain that executes all instructions!' },

  { topic:'CS', difficulty:'medium',
    question:'What is a boolean data type?',
    options:['A data type that can only be true or false','A special type of integer number','Used for storing text data only','Represents complex imaginary numbers'],
    correct:0, hint:'Named after mathematician George Boole, only two possible values.',
    professorAsk:'What is a boolean data type?',
    correctReaction:'True or False only! Boolean logic master! 💡',
    wrongReaction:'A special integer?! Boolean is NOT an integer! 😤',
    wrongComment:'Boolean = only true/false! Named after George Boole!' },

  { topic:'CS', difficulty:'medium',
    question:'What is the primary purpose of a firewall?',
    options:['Monitor and control incoming and outgoing network traffic','Prevent the computer from overheating physically','Speed up the internet connection','Securely store user passwords'],
    correct:0, hint:'It is a network security barrier.',
    professorAsk:'What does a firewall do?',
    correctReaction:'Network security and traffic control! 🔥🧱',
    wrongReaction:'Prevent overheating?! That is literally a FAN and heatsink! 😡',
    wrongComment:'Firewall = network security barrier, filters traffic by rules!' },

  { topic:'CS', difficulty:'easy',
    question:'What is cloud computing?',
    options:['Delivering computing services like servers and storage over the internet','Doing calculations while looking at clouds outside','Software specifically for weather prediction','Computing done wirelessly without any cables'],
    correct:0, hint:'Think of using someone else\'s powerful computers via the internet.',
    professorAsk:'Define cloud computing!',
    correctReaction:'On-demand computing services over internet! ☁️',
    wrongReaction:'Calculations while looking at clouds?! HEAD IN THE BOOKS! 😤',
    wrongComment:'Cloud = remote servers for compute, storage, and services over internet!' },

  { topic:'CS', difficulty:'hard',
    question:'What is the difference between symmetric and asymmetric encryption?',
    options:['Symmetric uses one key for both, asymmetric uses public/private key pair','Symmetric is always more secure','Asymmetric uses the same key for both operations','There is no practical difference between them'],
    correct:0, hint:'Think about how many keys are involved in each type.',
    professorAsk:'Symmetric vs Asymmetric encryption?',
    correctReaction:'One key vs Key pair! Security expert! 🔐',
    wrongReaction:'No practical difference?! Then why use both?! 😡',
    wrongComment:'Symmetric=1 shared key (AES), Asymmetric=public+private pair (RSA)!' },

  { topic:'CS', difficulty:'hard',
    question:'What is the CAP theorem in distributed systems?',
    options:['You can only guarantee 2 of: Consistency, Availability, Partition tolerance','CAP stands for Computer Automated Processing','All three properties can always be achieved','Only applies to databases not distributed systems'],
    correct:0, hint:'In distributed systems, there is always a trade-off.',
    professorAsk:'What is the CAP theorem?',
    correctReaction:'Pick only 2 of C, A, P! Distributed systems master! 🌐',
    wrongReaction:'Computer Automated Processing?! That is not even a thing! 😡',
    wrongComment:'CAP: Consistency + Availability + Partition Tolerance - pick any 2!' },

  { topic:'CS', difficulty:'medium',
    question:'What is the difference between HTTP and HTTPS?',
    options:['HTTPS adds SSL/TLS encryption for secure communication','HTTPS is always slower than HTTP','There is no real difference between them','HTTPS only works on mobile devices'],
    correct:0, hint:'The S stands for something related to security.',
    professorAsk:'HTTP vs HTTPS - what is the difference?',
    correctReaction:'SSL/TLS encryption! Security-conscious student! 🔒',
    wrongReaction:'No real difference?! Banks would disagree! 😡',
    wrongComment:'HTTPS = HTTP + SSL/TLS encryption! The S = Secure!' },

  { topic:'CS', difficulty:'medium',
    question:'What does an IDE stand for?',
    options:['Integrated Development Environment','Internet Development Engine','Intelligent Debugging Extension','Internal Data Executor'],
    correct:0, hint:'It is a software application that provides tools for writing code.',
    professorAsk:'What does IDE stand for?',
    correctReaction:'Integrated Development Environment! Code tools expert! 💻',
    wrongReaction:'Internet Development Engine?! This is not the web! 😤',
    wrongComment:'IDE = Integrated Development Environment (VS Code, IntelliJ, Eclipse)!' },

  { topic:'CS', difficulty:'easy',
    question:'What is a bug in programming?',
    options:['An error or flaw in the program that causes incorrect behavior','A literal insect that entered the computer hardware','A feature that was added without documentation','A virus that attacks the computer'],
    correct:0, hint:'Named after an actual insect found in early computers!',
    professorAsk:'What is a programming bug?',
    correctReaction:'An error causing incorrect behavior! History lesson too! 🐛',
    wrongReaction:'A literal insect?! Check your computer then! 😤',
    wrongComment:'Bug = error in code! Term from Grace Hopper finding actual moth in 1947!' },

  { topic:'CS', difficulty:'medium',
    question:'What is machine learning in simple terms?',
    options:['Computers learning patterns from data to make predictions without explicit programming','Teaching machines to speak human languages','A type of computer hardware upgrade','Programming robots to walk and move'],
    correct:0, hint:'It learns from examples rather than following fixed rules.',
    professorAsk:'Define machine learning!',
    correctReaction:'Learning from data patterns! AI awareness! 🤖',
    wrongReaction:'Teaching machines to speak?! That is NLP, different thing! 😡',
    wrongComment:'ML = algorithms that improve through experience/data without explicit rules!' },

  { topic:'CS', difficulty:'hard',
    question:'What is Big O notation O(1)?',
    options:['Constant time - execution time does not depend on input size','The algorithm takes one second always','The slowest possible algorithm','Only works for single element inputs'],
    correct:0, hint:'No matter how large the input is, time stays the same.',
    professorAsk:'What does O(1) mean in Big O notation?',
    correctReaction:'Constant time! Input size does not matter! Perfect! ⚡',
    wrongReaction:'Takes one second?! O(1) is about scaling not duration! 😡',
    wrongComment:'O(1) = constant time, always same speed regardless of input size!' }
];

/* ============================================================
   Shuffle and Randomize Answer Positions
   ============================================================ */
function randomizeAnswers(q) {
  const opts = q.options.map((text, i) => ({ text, isCorrect: i === q.correct }));
  // Fisher-Yates shuffle
  for (let i = opts.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [opts[i], opts[j]] = [opts[j], opts[i]];
  }
  const newCorrect = opts.findIndex(o => o.isCorrect);
  return { ...q, options: opts.map(o => o.text), correct: newCorrect };
}

function shuffleAndPick(arr, count) {
  const shuffled = [...arr].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count).map(q => randomizeAnswers(q));
}
