/* ============================================================
   ESCAPE THE VIVA - Questions Bank (200 Questions)
   Designed and Expanded for Bhavish's Game
   ============================================================ */

const allQuestions = [
  // ========== OOP (Original + Expanded) ==========
  { topic:'OOP', difficulty:'easy',
    question:'What does OOP stand for?',
    options:['Object Oriented Programming','Only One Program','Order of Pizza Pls',"I don't know sir"],
    correct:0, hint:'Think about the "O" - it relates to real-world things like cars and animals.',
    professorAsk:'What does OOP stand for?',
    correctReaction:'Good! At least you know something. 👍',
    wrongReaction:'Order of Pizza?? Are you in a hotel or college? 😤',
    wrongComment:'This is why students are failing these days!' },
  { topic:'OOP', difficulty:'easy',
    question:'What is Encapsulation in OOP?',
    options:['Hiding data and methods inside a class','Putting code in capsules','A medicine term','Wrapping gifts nicely'],
    correct:0, hint:'Think of a capsule that hides what is inside it.',
    professorAsk:'Tell me about Encapsulation!',
    correctReaction:'Correct! Data hiding! You studied! 👏',
    wrongReaction:'Putting code in capsules?! Which pharmacy taught you? 😡',
    wrongComment:'Encapsulation is DAY ONE topic!' },
  { topic:'OOP', difficulty:'easy',
    question:'What is Inheritance in OOP?',
    options:['Child class gets parent class properties','Getting money from parents','Copying homework','None of the above'],
    correct:0, hint:'Think parent and child - what does a child get from parents?',
    professorAsk:'Explain Inheritance!',
    correctReaction:"Yes! Parent to child! Not your dad's money though! 😄",
    wrongReaction:'Getting money from parents?! Wrong subject entirely! 😤',
    wrongComment:'Inheritance = Child class extending Parent class!' },
  { topic:'OOP', difficulty:'medium',
    question:'What is Polymorphism?',
    options:['One interface, many forms','Many professors, one student','A shape-shifting animal','Greek food item'],
    correct:0, hint:'Poly = many, morph = form/shape.',
    professorAsk:'Define Polymorphism!',
    correctReaction:'Poly=many, morph=forms! Excellent! 🌟',
    wrongReaction:'Greek food?! This is Computer Science not a restaurant! 🤬',
    wrongComment:'POLY-MOR-PHISM! Repeat after me!' },
  { topic:'OOP', difficulty:'medium',
    question:'What is an Abstract Class?',
    options:['A class that cannot be instantiated directly','A class that is confusing','An art class','Class with no students'],
    correct:0, hint:'You cannot create an object directly from this type of class.',
    professorAsk:'What is an Abstract Class?',
    correctReaction:'Cannot be instantiated directly! Perfect! 💯',
    wrongReaction:'An art class?! Wrong department sir! 😤',
    wrongComment:'Abstract = incomplete blueprint you cannot build directly!' },
  { topic:'OOP', difficulty:'medium',
    question:'What is method overloading?',
    options:['Same method name with different parameters','A method working too hard','Overloading the CPU','Too many methods in a class'],
    correct:0, hint:'Same name, different signature - parameters differ.',
    professorAsk:'Explain method overloading!',
    correctReaction:'Same name, different signature! Correct! 👍',
    wrongReaction:'Method working too hard?! Like you should be doing! 😡',
    wrongComment:'Overloading = compile time polymorphism!' },
  { topic:'OOP', difficulty:'hard',
    question:'Which SOLID principle states a class should have only one reason to change?',
    options:['Single Responsibility Principle','Open Closed Principle','Change Management Principle','Professor Said So Principle'],
    correct:0, hint:'S in SOLID - Single something...',
    professorAsk:'Which SOLID principle limits class responsibility?',
    correctReaction:'SRP! Solid answer! Pun intended! 🎯',
    wrongReaction:'Professor Said So?! I say ZERO MARKS! 😡',
    wrongComment:'S in SOLID = Single Responsibility Principle!' },
  { topic:'OOP', difficulty:'hard',
    question:'What is the difference between method overloading and overriding?',
    options:['Overloading is compile-time, overriding is runtime polymorphism','They are the same thing','Overriding uses same parameters','Overloading only works in Java'],
    correct:0, hint:'One happens at compile time, one at runtime.',
    professorAsk:'Overloading vs Overriding - difference?',
    correctReaction:'Compile vs Runtime polymorphism! Expert! 🏆',
    wrongReaction:'They are same?! They are COMPLETELY different! 😡',
    wrongComment:'Overloading=compile time, Overriding=runtime!' },
  { topic:'OOP', difficulty:'medium',
    question:'What is Abstraction?',
    options:['Showing only essential features and hiding background details','Making things abstract and difficult','Deleting the code entirely','Painting an abstract painting'],
    correct:0, hint:'Like driving a car without knowing how the engine works.',
    professorAsk:'What is Abstraction in OOP?',
    correctReaction:'Essential features only! Very clear answer! 🚗',
    wrongReaction:'Painting?! Are you an artist or an engineer?! 😤',
    wrongComment:'Abstraction hides implementation details!' },
  { topic:'OOP', difficulty:'easy',
    question:'What are access modifiers in OOP?',
    options:['Keywords that set the accessibility of classes and methods','People who modify exams','Tools to hack accounts','Nothing important'],
    correct:0, hint:'public, private, protected...',
    professorAsk:'What are access modifiers?',
    correctReaction:'Visibility control! Spot on! 👀',
    wrongReaction:'Hack accounts?! You belong in jail, not my class! 😡',
    wrongComment:'Access modifiers define scope and visibility!' },
  { topic:'OOP', difficulty:'medium',
    question:'What does the "protected" access modifier do?',
    options:['Accessible within same package and subclasses','Accessible only in the same class','Accessible everywhere','It protects from viruses'],
    correct:0, hint:'Like private, but allows children to inherit.',
    professorAsk:'Explain the "protected" modifier!',
    correctReaction:'Package and subclasses! You know your scopes! 🛡️',
    wrongReaction:'Protects from viruses?! I need an antivirus for your answers! 😤',
    wrongComment:'Protected = accessible in child classes!' },
  { topic:'OOP', difficulty:'hard',
    question:'What is the Diamond Problem in OOP?',
    options:['Ambiguity arising from multiple inheritance','When you cannot afford a diamond','A hard coding problem','A graphics rendering error'],
    correct:0, hint:'Two parents have the same method, child doesn\'t know which to inherit.',
    professorAsk:'What is the Diamond Problem?',
    correctReaction:'Multiple inheritance ambiguity! Brilliant! 💎',
    wrongReaction:'Cannot afford a diamond?! You definitely cannot afford to fail this viva! 😡',
    wrongComment:'Diamond problem occurs in languages supporting multiple inheritance like C++!' },
  { topic:'OOP', difficulty:'medium',
    question:'What is early binding also known as?',
    options:['Static binding or compile-time binding','Waking up early to code','Connecting cables early','Fast compilation'],
    correct:0, hint:'Happens before the program runs.',
    professorAsk:'What is early binding?',
    correctReaction:'Compile-time binding! Correct! ⚡',
    wrongReaction:'Waking up early?! You are sleeping in my viva right now! 😤',
    wrongComment:'Early binding = resolved by compiler at compile time!' },
  { topic:'OOP', difficulty:'medium',
    question:'What is late binding?',
    options:['Dynamic binding or runtime binding','Submitting assignments late','Compiling at night','Slow execution'],
    correct:0, hint:'Happens while the program is actually running.',
    professorAsk:'What is late binding?',
    correctReaction:'Runtime binding! Excellent! 🏃',
    wrongReaction:'Submitting late?! I will give you a late ZERO! 😡',
    wrongComment:'Late binding happens via virtual methods at runtime!' },
  { topic:'OOP', difficulty:'easy',
    question:'What is a class?',
    options:['A blueprint from which objects are created','A classroom in college','A collection of students','A variable type'],
    correct:0, hint:'It defines the structure and behavior for future objects.',
    professorAsk:'What is a class?',
    correctReaction:'A blueprint! Basic but perfect! 🏗️',
    wrongReaction:'A classroom?! You clearly haven\'t been in one! 😤',
    wrongComment:'Class = Blueprint, Object = Realization!' },
  { topic:'OOP', difficulty:'easy',
    question:'What is an object in OOP?',
    options:['An instance of a class','Something you throw at the professor','A physical item on your desk','A literal string'],
    correct:0, hint:'Created from a blueprint.',
    professorAsk:'What is an object?',
    correctReaction:'Instance of a class! Spot on! 📦',
    wrongReaction:'Throw at me?! I will throw you out! 😡',
    wrongComment:'Object is a real-world entity born from a Class!' },
  { topic:'OOP', difficulty:'hard',
    question:'What is a copy constructor?',
    options:['A constructor that initializes an object using another object of the same class','A student copying during exams','A tool to copy-paste code','A method that returns a duplicate string'],
    correct:0, hint:'It creates a clone of an existing object.',
    professorAsk:'Define copy constructor!',
    correctReaction:'Clones an object! Expert level! 👯',
    wrongReaction:'Copying during exams?! Confession accepted. FAIL! 😤',
    wrongComment:'Copy constructor takes a reference to its own class!' },
  { topic:'OOP', difficulty:'hard',
    question:'What is the difference between composition and aggregation?',
    options:['Composition is a strict part-of relationship (death together), Aggregation is weak','They are exactly identical','Aggregation is stronger than composition','Composition applies only to music'],
    correct:0, hint:'In one, if the parent dies, the child dies. In the other, the child survives.',
    professorAsk:'Composition vs Aggregation?',
    correctReaction:'Strong vs weak relationships! Architectural master! 🏛️',
    wrongReaction:'Applies to music?! This is CS, not a symphony! 😡',
    wrongComment:'Composition = Strong (Room in House), Aggregation = Weak (Student in Class)!' },
  { topic:'OOP', difficulty:'medium',
    question:'What is an Interface in OOP?',
    options:['A completely abstract class that groups related empty methods','The UI of an application','A cable connecting two PCs','The screen of your laptop'],
    correct:0, hint:'It defines WHAT a class must do, but not HOW.',
    professorAsk:'What is an Interface?',
    correctReaction:'Contract of empty methods! Well articulated! 📜',
    wrongReaction:'UI of app?! Wrong context completely! 😤',
    wrongComment:'Interface defines behavior that implementing classes must fulfill!' },
  { topic:'OOP', difficulty:'medium',
    question:'Can we instantiate an Interface directly?',
    options:['No, because it is incomplete','Yes, easily','Only on Tuesdays','Yes, if we use the new keyword twice'],
    correct:0, hint:'You can\'t build a house from just a sketch.',
    professorAsk:'Can you create an object of an Interface?',
    correctReaction:'No! It is incomplete! Perfect! 🚫',
    wrongReaction:'On Tuesdays?! What kind of logic is that?! 😡',
    wrongComment:'Interfaces and Abstract classes CANNOT be instantiated directly!' },
  { topic:'OOP', difficulty:'hard',
    question:'What does the "L" stand for in SOLID principles?',
    options:['Liskov Substitution Principle','Low Coupling Principle','Late Binding Principle','Lazy Loading Principle'],
    correct:0, hint:'Named after Barbara...',
    professorAsk:'What is the L in SOLID?',
    correctReaction:'Liskov Substitution! Very advanced! 🎯',
    wrongReaction:'Lazy Loading?! That describes your study habits! 😤',
    wrongComment:'LSP: Derived classes must be substitutable for their base classes!' },
  { topic:'OOP', difficulty:'hard',
    question:'What is a pure virtual function?',
    options:['A virtual function with no implementation, assigned to 0 in C++','A function that only returns pure water','A function with no bugs','A static method'],
    correct:0, hint:'Used in C++ to make a class abstract.',
    professorAsk:'What is a pure virtual function?',
    correctReaction:'No implementation, makes class abstract! Brilliant! 💧',
    wrongReaction:'Pure water?! Are you a plumber?! 😡',
    wrongComment:'virtual void func() = 0; defines a pure virtual function!' },

  // ========== Java (Original + Expanded) ==========
  { topic:'Java', difficulty:'easy',
    question:"What does the 'this' keyword refer to in Java?",
    options:['The current object instance','The previous year syllabus','This college only','I am not sure sir'],
    correct:0, hint:'It refers to the object that is currently being used.',
    professorAsk:"Explain 'this' keyword in Java!",
    correctReaction:'Refers to current object! Correct! 🎯',
    wrongReaction:"Refers to previous year?! What kind of answer is THIS?! 😡",
    wrongComment:'THIS keyword = THIS current object! Simple!' },
  { topic:'Java', difficulty:'medium',
    question:"What is the output of System.out.println(1 + 2 + '3')?",
    options:['33','6','123','Compilation Error'],
    correct:0, hint:'1+2 first (int), then result + char 3.',
    professorAsk:"Quick! Output of: System.out.println(1 + 2 + '3')?",
    correctReaction:'33! You understand type coercion! 🏆',
    wrongReaction:'WRONG! Java arithmetic is not forgiving! 😡',
    wrongComment:"1+2=3 (int), 3+'3'=33 (char addition)! Basics!" },
  { topic:'Java', difficulty:'easy',
    question:'What does JVM stand for?',
    options:['Java Virtual Machine','Java Very Much Sir','Just Virtual Memory','Java Viva Machine'],
    correct:0, hint:'It is the engine that runs Java programs.',
    professorAsk:'What is JVM?',
    correctReaction:'Java Virtual Machine! Well done! ☕',
    wrongReaction:'Java Viva Machine?! Are you mocking me?! 😤',
    wrongComment:'JVM = Java Virtual Machine! Makes Java portable!' },
  { topic:'Java', difficulty:'medium',
    question:'What is the difference between == and .equals() in Java?',
    options:['== checks reference, .equals() checks value','They are exactly the same','== is faster always','equals() is only for Strings'],
    correct:0, hint:'One checks memory address, one checks actual content.',
    professorAsk:'== vs .equals() in Java?',
    correctReaction:'Reference vs Value comparison! You studied! 🌟',
    wrongReaction:'They are same?! They are absolutely NOT same! 😡',
    wrongComment:'== checks if same object, equals() checks same content!' },
  { topic:'Java', difficulty:'easy',
    question:'What is a constructor in Java?',
    options:['A method that initializes an object','A person who builds things','An alternative to main method','A special type of loop'],
    correct:0, hint:'It runs automatically when you create a new object.',
    professorAsk:'What is a constructor?',
    correctReaction:'Initializes the object! Perfect! 🏗️',
    wrongReaction:'A person who builds things?! Civil engineering is next door! 😤',
    wrongComment:'Constructor = same name as class, no return type!' },
  { topic:'Java', difficulty:'medium',
    question:'What does the final keyword do in Java?',
    options:['Prevents further modification','Marks last line of code','Ends the program execution','It is a final exam keyword'],
    correct:0, hint:'Final means it cannot be changed after assignment.',
    professorAsk:'What does the final keyword do?',
    correctReaction:'Prevents modification! Locks it down! 🔒',
    wrongReaction:'Final exam keyword?! IS THIS A COMEDY SHOW?! 😡',
    wrongComment:'final variable=constant, final method=no override, final class=no extend!' },
  { topic:'Java', difficulty:'hard',
    question:'What is the difference between ArrayList and LinkedList in Java?',
    options:['ArrayList uses array, LinkedList uses nodes - different access speeds','They are completely identical','LinkedList is faster always','ArrayList uses more memory always'],
    correct:0, hint:'Think about how data is stored and how fast you can access it.',
    professorAsk:'ArrayList vs LinkedList - go!',
    correctReaction:'Array vs Node structure! Access vs Insert speed! Expert! 🌟',
    wrongReaction:'Completely identical?! Then why do both exist?! 😡',
    wrongComment:'ArrayList=O(1) access, LinkedList=O(1) insert/delete at ends!' },
  { topic:'Java', difficulty:'hard',
    question:'What is the super keyword used for in Java?',
    options:['To refer to immediate parent class object','To make the program run faster','To declare a superhero class','To bypass access modifiers'],
    correct:0, hint:'Think of parent class reference.',
    professorAsk:'What is the "super" keyword?',
    correctReaction:'Parent class reference! Excellent! 🦸‍♂️',
    wrongReaction:'Superhero class?! Are you watching Marvel during lectures?! 😤',
    wrongComment:'super() calls parent constructor, super.var calls parent variable!' },
  { topic:'Java', difficulty:'medium',
    question:'Which package is imported by default in every Java program?',
    options:['java.lang','java.util','java.io','java.default'],
    correct:0, hint:'Contains String, System, Math classes.',
    professorAsk:'Which package is imported by default?',
    correctReaction:'java.lang! You know the foundations! 📦',
    wrongReaction:'java.default?! Stop inventing packages! 😡',
    wrongComment:'java.lang is automatically imported in all Java files!' },
  { topic:'Java', difficulty:'medium',
    question:'What is a static method in Java?',
    options:['A method that belongs to the class, not the object','A method that cannot be moved','A method that causes static electricity','A method with no return type'],
    correct:0, hint:'You can call it without creating an instance.',
    professorAsk:'Explain static methods!',
    correctReaction:'Belongs to the class! Right on point! ⚡',
    wrongReaction:'Static electricity?! Are we in Physics class?! 😤',
    wrongComment:'Static methods are called using ClassName.methodName()!' },
  { topic:'Java', difficulty:'hard',
    question:'What is the difference between throw and throws in Java?',
    options:['throw actually throws an exception, throws declares it in method signature','They are just singular and plural forms','throws is used in catch blocks','There is no difference'],
    correct:0, hint:'One is an action, the other is a warning label.',
    professorAsk:'throw vs throws?',
    correctReaction:'Action vs Declaration! Exception handling expert! 🚨',
    wrongReaction:'Singular and plural?! This is not an English exam! 😡',
    wrongComment:'throw new Exception(), void method() throws Exception!' },
  { topic:'Java', difficulty:'hard',
    question:'What is a Garbage Collector in Java?',
    options:['A background thread that destroys unreferenced objects to free memory','A person who cleans the computer','A tool to delete bad code automatically','A folder for deleted files'],
    correct:0, hint:'It handles memory management automatically.',
    professorAsk:'What does the Garbage Collector do?',
    correctReaction:'Frees unreferenced memory! Clean and precise! 🗑️',
    wrongReaction:'Cleans the computer?! With a broom?! 😤',
    wrongComment:'Garbage Collector automatically runs System.gc() in background!' },
  { topic:'Java', difficulty:'medium',
    question:'Is Java Pass-by-Value or Pass-by-Reference?',
    options:['Strictly Pass-by-Value (even object references are passed by value)','Strictly Pass-by-Reference','Both depending on data type','Neither'],
    correct:0, hint:'It copies the value (which might be a reference).',
    professorAsk:'Is Java pass-by-value or pass-by-reference?',
    correctReaction:'Strictly pass-by-value! You didn\'t fall for the trap! 🪤',
    wrongReaction:'Pass by reference?! Have you ever read the Java documentation?! 😡',
    wrongComment:'Java is ALWAYS pass-by-value. It passes the value of the reference!' },
  { topic:'Java', difficulty:'medium',
    question:'What is the root class of all classes in Java?',
    options:['Object class','Main class','Root class','System class'],
    correct:0, hint:'The mother of all classes.',
    professorAsk:'What is the root class of Java?',
    correctReaction:'java.lang.Object! Perfect hierarchy knowledge! 🌳',
    wrongReaction:'Main class?! No, no, NO! 😤',
    wrongComment:'Every Java class implicitly extends Object!' },
  { topic:'Java', difficulty:'easy',
    question:'Can we override a static method in Java?',
    options:['No, because they belong to the class (method hiding occurs instead)','Yes, anytime','Only in abstract classes','Yes, but only once'],
    correct:0, hint:'They belong to the class, not the instance.',
    professorAsk:'Can you override a static method?',
    correctReaction:'No, it is method hiding! Impressive detail! 🛡️',
    wrongReaction:'Yes?! Have you ever compiled code in your life?! 😡',
    wrongComment:'Static methods are resolved at compile time, hence no overriding!' },
  { topic:'Java', difficulty:'hard',
    question:'What is the difference between String, StringBuffer, and StringBuilder?',
    options:['String is immutable, StringBuffer is thread-safe mutable, StringBuilder is non-thread-safe mutable','They are identical but with different lengths','String is for text, buffers are for numbers','None of the above'],
    correct:0, hint:'Immutability vs Thread-Safety vs Speed.',
    professorAsk:'String vs StringBuffer vs StringBuilder?',
    correctReaction:'Immutability and thread safety explained! Flawless! 📝',
    wrongReaction:'Buffers are for numbers?! Are you guessing?! 😤',
    wrongComment:'String=immutable, StringBuffer=sync/safe, StringBuilder=unsync/fast!' },
  { topic:'Java', difficulty:'medium',
    question:'What are Wrapper classes in Java?',
    options:['Classes that encapsulate primitive types into objects (e.g., Integer for int)','Classes that wrap text in console','Classes used for packing JAR files','Security classes that wrap viruses'],
    correct:0, hint:'They turn basic types into full objects.',
    professorAsk:'What are Wrapper classes?',
    correctReaction:'Encapsulates primitives! Autoboxing master! 🎁',
    wrongReaction:'Wrapping text?! This is Java, not Microsoft Word! 😡',
    wrongComment:'Wrapper classes (Integer, Boolean, etc.) allow primitives to be used in Collections!' },
  { topic:'Java', difficulty:'hard',
    question:'What is synchronization in Java?',
    options:['Controlling access of multiple threads to shared resources','Making sure audio matches video','Syncing code to GitHub','Downloading latest Java updates'],
    correct:0, hint:'Prevents thread interference.',
    professorAsk:'Explain thread synchronization!',
    correctReaction:'Controls shared resource access! Multithreading pro! 🚦',
    wrongReaction:'Audio matches video?! Am I a media player to you?! 😤',
    wrongComment:'synchronized keyword prevents race conditions in multithreading!' },
  { topic:'Java', difficulty:'hard',
    question:'What does the transient keyword do?',
    options:['Prevents a variable from being serialized','Makes a variable temporary in memory','Allows variables to jump classes','It is a networking term only'],
    correct:0, hint:'Used during object serialization to hide data.',
    professorAsk:'What is the transient keyword?',
    correctReaction:'Prevents serialization! Excellent memory control! 👻',
    wrongReaction:'Temporary in memory?! No, that is garbage collection! 😡',
    wrongComment:'transient fields are ignored during ObjectOutputStream serialization!' },
  { topic:'Java', difficulty:'medium',
    question:'What is an Interface in Java 8 and onwards?',
    options:['Can contain abstract methods, plus default and static methods with implementation','Only contains purely abstract methods','Can contain instance variables','Replaced abstract classes entirely'],
    correct:0, hint:'Java 8 added new features to interfaces to prevent breaking changes.',
    professorAsk:'How did Interfaces change in Java 8?',
    correctReaction:'Default and static methods! Up to date with modern Java! ☕',
    wrongReaction:'Only purely abstract?! You are living in Java 7 era! 😤',
    wrongComment:'Java 8 introduced default methods to allow backward compatibility!' },

  // ========== DSA (Original + Expanded) ==========
  { topic:'DSA', difficulty:'easy',
    question:'What is the time complexity of binary search?',
    options:['O(log n)','O(n)','O(n log n)','O(1)'],
    correct:0, hint:'The array is halved each time you search.',
    professorAsk:'Time complexity of binary search?',
    correctReaction:'O(log n)! Halving each step! Perfect! 📊',
    wrongReaction:'O(n)?! That is LINEAR search! Different thing! 😡',
    wrongComment:'Binary search HALVES the search space each time!' },
  { topic:'DSA', difficulty:'easy',
    question:'Which data structure uses the LIFO principle?',
    options:['Stack','Queue','LinkedList','My dying brain cells'],
    correct:0, hint:'Think of a stack of plates - you take from the top.',
    professorAsk:'Which data structure follows LIFO?',
    correctReaction:'Stack! Last In First Out! Correct! 📚',
    wrongReaction:'Your brain cells?! LIFO of your grades too! 😤',
    wrongComment:'Stack=LIFO (Last In First Out), Queue=FIFO!' },
  { topic:'DSA', difficulty:'medium',
    question:'What is the worst case time complexity of QuickSort?',
    options:['O(n²)','O(n log n)','O(log n)','O(n)'],
    correct:0, hint:'Happens when pivot is always the smallest or largest element.',
    professorAsk:'Worst case time complexity of QuickSort?',
    correctReaction:'O(n²) when pivot is always min/max! Correct! 🎯',
    wrongReaction:'O(n log n) is the AVERAGE case, not worst! 😡',
    wrongComment:'QuickSort worst case: sorted array with bad pivot choice!' },
  { topic:'DSA', difficulty:'easy',
    question:'What is the primary use of a Hash Table?',
    options:['Fast key-value pair lookup in O(1)','Only for hashing passwords','Creating HTML tables faster','Organizing breakfast items'],
    correct:0, hint:'Average case lookup is constant time.',
    professorAsk:'What is Hash Table used for?',
    correctReaction:'O(1) average lookup! Brilliant answer! 🔑',
    wrongReaction:'Organizing breakfast?! GET OUT OF MY VIVA ROOM! 😡',
    wrongComment:'Hash Table = O(1) average for search, insert, delete!' },
  { topic:'DSA', difficulty:'medium',
    question:'What property does a Binary Search Tree (BST) maintain?',
    options:['Left child < Parent < Right child','Right child < Parent < Left child','Random order throughout','Only alphabetical ordering'],
    correct:0, hint:'Values on the left are smaller, values on right are larger.',
    professorAsk:'What is the BST property?',
    correctReaction:'Left smaller, right larger! Perfect BST knowledge! 🌳',
    wrongReaction:'Random order?! Then it is just a regular tree! 😤',
    wrongComment:'BST: Left subtree < Root < Right subtree! Always!' },
  { topic:'DSA', difficulty:'hard',
    question:'What is the time complexity of Dijkstra\'s algorithm with a min-heap?',
    options:['O((V + E) log V)','O(V²)','O(E log V)','O(V log E)'],
    correct:0, hint:'V = vertices, E = edges. The heap helps reduce complexity.',
    professorAsk:'Dijkstra\'s complexity with min-heap?',
    correctReaction:'O((V+E) log V)! Algorithm master! 🏆',
    wrongReaction:'O(V²) is basic Dijkstra without heap! 😡',
    wrongComment:'With min-heap: O((V+E)logV). Without: O(V²)!' },
  { topic:'DSA', difficulty:'easy',
    question:'What is a Queue?',
    options:['A data structure following FIFO (First In First Out)','A line of students waiting to fail','A random access storage','A tree with one branch'],
    correct:0, hint:'Like waiting in a line at the cafeteria.',
    professorAsk:'What is a Queue data structure?',
    correctReaction:'FIFO! Just like a real queue! 🚶‍♂️🚶‍♀️',
    wrongReaction:'Students waiting to fail?! DO NOT TEST MY PATIENCE! 😤',
    wrongComment:'Queue = FIFO. First element added is first to be removed!' },
  { topic:'DSA', difficulty:'medium',
    question:'What is the difference between a Tree and a Graph?',
    options:['A tree cannot have cycles, a graph can have cycles','Trees are green, graphs have coordinates','They are mathematically exactly the same','Graphs only have nodes, trees only have edges'],
    correct:0, hint:'You can loop around in one, but not the other.',
    professorAsk:'Tree vs Graph - main difference?',
    correctReaction:'No cycles in trees! Excellent graph theory! 🌲',
    wrongReaction:'Trees are green?! Are we in Botany class?! 😡',
    wrongComment:'A Tree is a restricted Graph (Connected, Undirected, Acyclic)!' },
  { topic:'DSA', difficulty:'medium',
    question:'Which traversal of a BST gives elements in sorted order?',
    options:['Inorder Traversal','Preorder Traversal','Postorder Traversal','Level Order Traversal'],
    correct:0, hint:'Left, Root, Right.',
    professorAsk:'How to get sorted elements from a BST?',
    correctReaction:'Inorder gives sorted order! Spot on! 📈',
    wrongReaction:'Preorder?! That gives root first, not sorted! 😤',
    wrongComment:'Inorder BST traversal = Ascending sorted order!' },
  { topic:'DSA', difficulty:'hard',
    question:'What is an AVL Tree?',
    options:['A self-balancing Binary Search Tree where height difference is at most 1','A tree used for Aviational tracking','A binary tree with no leaves','A tree that grows dynamically on hard drive'],
    correct:0, hint:'Named after Adelson-Velsky and Landis, it rotates to stay balanced.',
    professorAsk:'What is an AVL tree?',
    correctReaction:'Self-balancing BST! Height-balanced! Perfect! ⚖️',
    wrongReaction:'Aviational tracking?! Who is teaching you these things?! 😡',
    wrongComment:'AVL Tree maintains O(log n) height by rotating on insertions/deletions!' },
  { topic:'DSA', difficulty:'hard',
    question:'What is the time complexity to insert an element into a Min-Heap?',
    options:['O(log n)','O(1)','O(n)','O(n log n)'],
    correct:0, hint:'You insert at the bottom and bubble up.',
    professorAsk:'Time complexity of Heap Insertion?',
    correctReaction:'O(log n) to heapify up! Correct! ⬆️',
    wrongReaction:'O(1)?! Only peeking at the root is O(1)! 😤',
    wrongComment:'Insertion requires heapifying up the tree height: O(log n)!' },
  { topic:'DSA', difficulty:'medium',
    question:'What is a Graph BFS?',
    options:['Breadth-First Search using a Queue to explore layer by layer','Best Friend Search on social media','A sorting algorithm for graphs','Finding the shortest path always'],
    correct:0, hint:'Layer by layer exploration.',
    professorAsk:'Explain Graph BFS!',
    correctReaction:'Breadth-First using Queue! Standard algorithm! 🌐',
    wrongReaction:'Best Friend Search?! Get off Facebook and study! 😡',
    wrongComment:'BFS uses a Queue to visit nodes level-by-level!' },
  { topic:'DSA', difficulty:'medium',
    question:'What is a Graph DFS?',
    options:['Depth-First Search using a Stack/Recursion to explore deep first','Direct File System','A type of binary tree','Deleting First Search'],
    correct:0, hint:'Go as deep as possible before backtracking.',
    professorAsk:'Explain Graph DFS!',
    correctReaction:'Depth-First using Stack/Recursion! Very good! 🕳️',
    wrongReaction:'Deleting First?! You are deleting your marks! 😤',
    wrongComment:'DFS uses a Stack (or call stack via recursion) to explore paths!' },
  { topic:'DSA', difficulty:'hard',
    question:'How does Dynamic Programming differ from Divide and Conquer?',
    options:['DP stores overlapping subproblems (Memoization), D&C solves disjoint subproblems','D&C is always faster than DP','DP is only for graphs, D&C is for arrays','There is no difference'],
    correct:0, hint:'One remembers past answers to save time.',
    professorAsk:'Dynamic Programming vs Divide & Conquer?',
    correctReaction:'Overlapping vs Disjoint subproblems! Masterful! 🧠',
    wrongReaction:'No difference?! Fibonacci recursive vs DP tells a different story! 😡',
    wrongComment:'DP optimizes by storing solutions to overlapping subproblems!' },
  { topic:'DSA', difficulty:'easy',
    question:'What is the time complexity of looking up an element in a Linked List?',
    options:['O(n)','O(1)','O(log n)','O(n²)'],
    correct:0, hint:'You must traverse node by node from the head.',
    professorAsk:'Lookup time in a Linked List?',
    correctReaction:'O(n) linear search! Correct! 🔗',
    wrongReaction:'O(1)?! It is not an array! You have to traverse! 😤',
    wrongComment:'Linked lists do not have random access. You must traverse from head: O(n)!' },
  { topic:'DSA', difficulty:'medium',
    question:'What is a Circular Queue?',
    options:['A queue where the last position connects back to the first to save space','A queue arranged in a physical circle','A queue that never ends','A queue specifically for rendering pie charts'],
    correct:0, hint:'Helps reuse empty spaces at the front of the array.',
    professorAsk:'What is a Circular Queue?',
    correctReaction:'Connects last to first! Very efficient! ♻️',
    wrongReaction:'Rendering pie charts?! What on earth are you imagining?! 😡',
    wrongComment:'Circular queue uses modulo arithmetic to wrap around array ends!' },
  { topic:'DSA', difficulty:'hard',
    question:'What is a Trie data structure primarily used for?',
    options:['Efficient string matching and autocomplete','Sorting numbers quickly','Balancing binary trees','Hashing objects'],
    correct:0, hint:'Often called a prefix tree.',
    professorAsk:'What is a Trie used for?',
    correctReaction:'String matching and autocomplete! Excellent! 🔤',
    wrongReaction:'Sorting numbers?! Use QuickSort for that! 😤',
    wrongComment:'Trie (Prefix Tree) gives O(L) string search time (L = word length)!' },
  { topic:'DSA', difficulty:'hard',
    question:'In a Hash Table, what is a collision?',
    options:['When two different keys map to the same hash index','When two tables crash into each other','When the table is completely full','When a hash function returns zero'],
    correct:0, hint:'Two different items trying to park in the same spot.',
    professorAsk:'What is a hash collision?',
    correctReaction:'Different keys, same index! Good hash knowledge! 💥',
    wrongReaction:'Tables crashing?! Stop playing racing games! 😡',
    wrongComment:'Collisions are handled via Chaining (LinkedList) or Open Addressing!' },
  { topic:'DSA', difficulty:'medium',
    question:'What is the Greedy algorithmic paradigm?',
    options:['Making the locally optimal choice at each stage with hope of finding global optimum','Eating all CPU resources','Trying every possible combination','Storing answers for future use'],
    correct:0, hint:'Take what looks best right now without worrying about the future.',
    professorAsk:'Explain the Greedy approach!',
    correctReaction:'Local optimum for global optimum! Well defined! 🤑',
    wrongReaction:'Eating CPU resources?! You are describing Chrome! 😤',
    wrongComment:'Greedy algorithms (like Kruskal/Prim) choose immediate best option!' },
  { topic:'DSA', difficulty:'easy',
    question:'What does a Stack Overflow mean?',
    options:['Exceeding the memory allocated for the call stack, often due to infinite recursion','A popular website for developers','Water spilling on the computer stack','When you compile too many times'],
    correct:0, hint:'Happens when recursion doesn\'t have a base case.',
    professorAsk:'What causes a Stack Overflow exception?',
    correctReaction:'Infinite recursion filling call stack! Spot on! 🥞',
    wrongReaction:'A website?! We are talking about the ERROR, not the website! 😡',
    wrongComment:'Stack Overflow error = too many nested method calls (no base case)!' },

  // ========== DBMS (Original + Expanded) ==========
  { topic:'DBMS', difficulty:'easy',
    question:'What does SQL stand for?',
    options:['Structured Query Language','Simple Question Language','Some Query Lagta Hai Sir','Student Question Loop'],
    correct:0, hint:'It is a language used to communicate with databases.',
    professorAsk:'What does SQL stand for?',
    correctReaction:'Structured Query Language! Correct! 🗄️',
    wrongReaction:'Some Query Lagta Hai?! WHAT IS THIS ANSWER?! 😡',
    wrongComment:'SQL = Structured Query Language! Industry standard!' },
  { topic:'DBMS', difficulty:'easy',
    question:'What is a Primary Key in a database?',
    options:['A unique identifier for each record in a table','The most important key on your keyboard','Always the first column in a table','The password to access the database'],
    correct:0, hint:'It uniquely identifies each row and cannot be null.',
    professorAsk:'Define a Primary Key!',
    correctReaction:'Uniquely identifies each row! Perfect! 🔑',
    wrongReaction:'Password to database?! That is not even close! 😤',
    wrongComment:'Primary Key = Unique + NOT NULL! Always!' },
  { topic:'DBMS', difficulty:'medium',
    question:'What is database normalization?',
    options:['Process of organizing data to reduce redundancy','Making all data look normal','Formatting the entire database','Creating a backup of the database'],
    correct:0, hint:'Think about eliminating repeated data.',
    professorAsk:'What is database normalization?',
    correctReaction:'Reduce redundancy, improve integrity! 🌟',
    wrongReaction:'Making data look normal?! WHAT is abnormal data?! 😡',
    wrongComment:'Normalization: 1NF, 2NF, 3NF, BCNF! Eliminate redundancy!' },
  { topic:'DBMS', difficulty:'medium',
    question:'What does ACID stand for in database transactions?',
    options:['Atomicity, Consistency, Isolation, Durability','A Chemical In the Database','Automated Computer Identification','All Correct Information Done'],
    correct:0, hint:'These are four properties that guarantee reliable transactions.',
    professorAsk:'What is ACID in database transactions?',
    correctReaction:'ACID properties! Transaction reliability expert! 💯',
    wrongReaction:'A Chemical In Database?! Call the chemistry department! 😡',
    wrongComment:'ACID: Atomicity, Consistency, Isolation, Durability!' },
  { topic:'DBMS', difficulty:'easy',
    question:'What is a Foreign Key?',
    options:['A key that references the Primary Key of another table','A key imported from another country','A secondary password for the database','A backup key for emergencies'],
    correct:0, hint:'It creates a link between two tables.',
    professorAsk:'What is a Foreign Key?',
    correctReaction:'Links tables together! Relational genius! 🔗',
    wrongReaction:'A key from another country?! DEPORTATION OF YOUR MARKS! 😤',
    wrongComment:'Foreign Key = creates relationship between tables!' },
  { topic:'DBMS', difficulty:'hard',
    question:'What is the difference between INNER JOIN and LEFT JOIN?',
    options:['INNER JOIN returns matching rows only, LEFT JOIN returns all left rows','They return the same results','LEFT JOIN is faster always','INNER JOIN returns all rows from both'],
    correct:0, hint:'Think about which rows are kept when there is no match.',
    professorAsk:'INNER JOIN vs LEFT JOIN - explain!',
    correctReaction:'Matching vs All-left rows! Database master! 🏆',
    wrongReaction:'Same results?! Run both queries and look! 😡',
    wrongComment:'INNER=only matches, LEFT=all left + matches, null for no match!' },
  { topic:'DBMS', difficulty:'easy',
    question:'What is DDL in SQL?',
    options:['Data Definition Language (CREATE, ALTER, DROP)','Data Deletion Loop','Database Design Layout','Direct Data Link'],
    correct:0, hint:'Commands that define the database structure.',
    professorAsk:'What is DDL?',
    correctReaction:'Data Definition Language! Correct command types! 🏗️',
    wrongReaction:'Data Deletion Loop?! That sounds like a nightmare! 😤',
    wrongComment:'DDL changes table structures. DML (INSERT/UPDATE) changes data!' },
  { topic:'DBMS', difficulty:'medium',
    question:'What is DML in SQL?',
    options:['Data Manipulation Language (INSERT, UPDATE, DELETE)','Data Migration Logic','Direct Memory Link','Database Master List'],
    correct:0, hint:'Commands that manipulate the actual data inside tables.',
    professorAsk:'What is DML?',
    correctReaction:'Data Manipulation Language! Modifies data! 📝',
    wrongReaction:'Direct Memory Link?! This is DBMS, not OS! 😡',
    wrongComment:'DML commands interact with the row data inside the defined tables!' },
  { topic:'DBMS', difficulty:'medium',
    question:'What is the purpose of a Database View?',
    options:['A virtual table based on the result-set of a SQL statement','A graphical user interface to view tables','To take screenshots of data','A physical copy of a table'],
    correct:0, hint:'It doesn\'t store data itself, just the query to fetch it.',
    professorAsk:'What is a View in DBMS?',
    correctReaction:'Virtual table from a query! Excellent security practice! 👁️',
    wrongReaction:'Screenshots of data?! Are you building an Instagram for databases?! 😤',
    wrongComment:'Views simplify complex queries and restrict data access without duplicating data!' },
  { topic:'DBMS', difficulty:'hard',
    question:'What is a Database Trigger?',
    options:['Procedural code automatically executed in response to certain events on a table','A button the database admin clicks','A warning when data gets too large','An error message generator'],
    correct:0, hint:'It fires automatically before or after an INSERT/UPDATE/DELETE.',
    professorAsk:'What is a Trigger?',
    correctReaction:'Auto-executed code on events! Very powerful! 🔫',
    wrongReaction:'A button admin clicks?! It is AUTOMATIC! 😡',
    wrongComment:'Triggers maintain audit trails and enforce complex business rules automatically!' },
  { topic:'DBMS', difficulty:'hard',
    question:'What data structure is typically used for database Indexing?',
    options:['B-Tree or B+ Tree','Linked List','Stack','Standard Array'],
    correct:0, hint:'Optimized for systems that read and write large blocks of data.',
    professorAsk:'Which data structure is used for indexes?',
    correctReaction:'B-Tree / B+ Tree! Disk access optimization! 🌳',
    wrongReaction:'Linked List?! Searching would take forever on a million rows! 😤',
    wrongComment:'B+ Trees keep data at the leaf nodes, allowing extremely fast range queries!' },
  { topic:'DBMS', difficulty:'medium',
    question:'What is First Normal Form (1NF)?',
    options:['Eliminating repeating groups, ensuring atomic values in columns','Making sure the table has a primary key only','Formatting column names to uppercase','Removing all numbers from text fields'],
    correct:0, hint:'Every cell must hold a single, indivisible value.',
    professorAsk:'What defines 1NF?',
    correctReaction:'Atomic values! No repeating groups! Good! ⚛️',
    wrongReaction:'Formatting to uppercase?! That is purely cosmetic! 😡',
    wrongComment:'1NF rule #1: ATOMICITY. One value per cell!' },
  { topic:'DBMS', difficulty:'hard',
    question:'What is a Deadlock in DBMS?',
    options:['Two or more transactions waiting for locks held by each other','When the database server crashes','When a query takes longer than 10 seconds','When you forget your database password'],
    correct:0, hint:'A circular wait condition for resources.',
    professorAsk:'What causes a database deadlock?',
    correctReaction:'Circular wait for locks! Concurrency expert! 🔒',
    wrongReaction:'Forgetting password?! That is user error, not a deadlock! 😤',
    wrongComment:'Deadlocks require the DB engine to kill one transaction to let the other proceed!' },
  { topic:'DBMS', difficulty:'medium',
    question:'What is the difference between TRUNCATE and DELETE?',
    options:['TRUNCATE is DDL and clears all rows faster without logging each row, DELETE is DML','They are exactly the same','DELETE cannot use WHERE clauses','TRUNCATE deletes the table structure completely'],
    correct:0, hint:'One is fully logged and allows row filtering, the other just resets the whole table.',
    professorAsk:'TRUNCATE vs DELETE?',
    correctReaction:'DDL vs DML! Logging difference! Brilliant! 🗑️',
    wrongReaction:'TRUNCATE deletes the structure?! No, that is the DROP command! 😡',
    wrongComment:'TRUNCATE resets the table quickly. DROP removes it entirely. DELETE filters rows!' },
  { topic:'DBMS', difficulty:'easy',
    question:'What is a NoSQL database?',
    options:['A non-relational database that doesn\'t use rigid tabular schemas','A database where SQL is strictly banned','A database with no search functionality','A completely offline database'],
    correct:0, hint:'Examples include MongoDB (document), Redis (key-value).',
    professorAsk:'What is NoSQL?',
    correctReaction:'Non-relational schemas! Welcome to modern web dev! 🍃',
    wrongReaction:'SQL strictly banned?! It is "Not Only SQL"! 😤',
    wrongComment:'NoSQL databases scale horizontally and handle unstructured data better!' },
  { topic:'DBMS', difficulty:'medium',
    question:'What is a Stored Procedure?',
    options:['Prepared SQL code that you can save and reuse over and over again','A procedure to restart the database server','A document explaining how to query','A backup file storage technique'],
    correct:0, hint:'Like a function, but stored directly inside the database.',
    professorAsk:'Explain Stored Procedures!',
    correctReaction:'Reusable SQL routines! Saves network traffic! 📦',
    wrongReaction:'A document explaining how to query?! RTFM is not a feature! 😡',
    wrongComment:'Stored Procedures pre-compile queries for faster execution and better security!' },
  { topic:'DBMS', difficulty:'hard',
    question:'What is Write-Ahead Logging (WAL)?',
    options:['Writing changes to a log before applying them to the actual database to ensure durability','Writing logs ahead of schedule','A logging framework for Node.js','Guessing database changes before they happen'],
    correct:0, hint:'Crucial for the "D" (Durability) in ACID in case of a crash.',
    professorAsk:'What is Write-Ahead Logging?',
    correctReaction:'Logs changes before applying! Durability guaranteed! 📝',
    wrongReaction:'Guessing changes?! Databases do not predict the future! 😤',
    wrongComment:'WAL ensures that if the DB crashes, uncommitted changes can be rolled back or applied upon restart!' },
  { topic:'DBMS', difficulty:'medium',
    question:'What does the GROUP BY clause do?',
    options:['Groups rows that have the same values into summary rows','Sorts the output alphabetically','Joins two tables together','Groups the database administrators'],
    correct:0, hint:'Usually used with aggregate functions (COUNT, MAX, MIN, SUM, AVG).',
    professorAsk:'What is GROUP BY used for?',
    correctReaction:'Summary rows with aggregates! SQL master! 📊',
    wrongReaction:'Groups administrators?! Do you think SQL manages HR?! 😡',
    wrongComment:'GROUP BY is essential for aggregations like counting students per department!' },
  { topic:'DBMS', difficulty:'easy',
    question:'What does the UNIQUE constraint do?',
    options:['Ensures all values in a column are different','Ensures the database has a unique name','Forces the column to accept only numbers','Automatically increments the ID'],
    correct:0, hint:'Similar to Primary Key, but can sometimes accept nulls.',
    professorAsk:'What is the UNIQUE constraint?',
    correctReaction:'All column values differ! Correct! ❄️',
    wrongReaction:'Unique database name?! Constraint applies to COLUMNS! 😤',
    wrongComment:'UNIQUE ensures no duplicate values in that specific column!' },
  { topic:'DBMS', difficulty:'hard',
    question:'What is Database Sharding?',
    options:['Splitting a large database horizontally across multiple servers','Breaking the hard drive into shards','Encrypting data into tiny pieces','Vertical scaling of RAM'],
    correct:0, hint:'Horizontal partitioning of data to distribute the load.',
    professorAsk:'What is Database Sharding?',
    correctReaction:'Horizontal partitioning across servers! Scaling expert! 🌍',
    wrongReaction:'Breaking the hard drive?! Please never touch server hardware! 😡',
    wrongComment:'Sharding allows massive databases to scale horizontally beyond a single machine\'s limits!' },

  // ========== OS (Original + Expanded) ==========
  { topic:'OS', difficulty:'medium',
    question:'What is a deadlock in Operating Systems?',
    options:['When two or more processes wait for each other indefinitely','When the computer suddenly dies','When sir locks the exam room door','System requires a restart to continue'],
    correct:0, hint:'Think of two processes each waiting for a resource the other holds.',
    professorAsk:'What is a deadlock in OS?',
    correctReaction:'Circular waiting! You actually read the textbook! 😲',
    wrongReaction:'Sir locks the door?! This is not a Bollywood film! 😡',
    wrongComment:'Deadlock conditions: Mutual exclusion + Hold & Wait + No preemption + Circular wait!' },
  { topic:'OS', difficulty:'medium',
    question:'What is Virtual Memory?',
    options:['Using disk storage as an extension of RAM','Memory that is completely fake','RAM used only in video games','A backup copy of RAM data'],
    correct:0, hint:'It allows programs to use more memory than physically available.',
    professorAsk:'Explain Virtual Memory!',
    correctReaction:'Disk extends RAM capacity! Perfect understanding! 💾',
    wrongReaction:'Fake memory?! YOUR knowledge is what is fake! 😤',
    wrongComment:'Virtual Memory = swap space on disk used as RAM extension!' },
  { topic:'OS', difficulty:'easy',
    question:'What is the role of the OS Scheduler?',
    options:['Decides which process gets CPU time and when','Schedules professor-student meetings','Creates the university timetable','Functions as an alarm clock'],
    correct:0, hint:'It manages which program runs on the processor.',
    professorAsk:'What does the OS Scheduler do?',
    correctReaction:'CPU process allocation! You understand OS! 🖥️',
    wrongReaction:'Schedules my meetings?! I schedule YOUR failure! 😡',
    wrongComment:'Scheduler = decides CPU allocation among competing processes!' },
  { topic:'OS', difficulty:'hard',
    question:'What is the difference between process and thread?',
    options:['Process is independent with own memory, thread shares process memory','They are exactly the same','Thread uses more memory than process','Process is faster than thread'],
    correct:0, hint:'One is heavyweight and isolated, the other is lightweight and shared.',
    professorAsk:'Process vs Thread - what is the difference?',
    correctReaction:'Independent vs shared memory! OS expert! 🌟',
    wrongReaction:'Exactly same?! Then why are they taught separately?! 😡',
    wrongComment:'Process=isolated memory space, Thread=shares parent process memory!' },
  { topic:'OS', difficulty:'easy',
    question:'What is an Operating System?',
    options:['System software acting as an interface between user hardware and software','The web browser you use','A type of computer hardware','A text editor for coding'],
    correct:0, hint:'Windows, Linux, macOS are examples.',
    professorAsk:'Define an Operating System!',
    correctReaction:'Software/Hardware interface! Fundamental! 💻',
    wrongReaction:'A text editor?! Are you compiling code in Microsoft Word?! 😤',
    wrongComment:'The OS manages hardware resources and provides services for computer programs!' },
  { topic:'OS', difficulty:'medium',
    question:'What is a Context Switch?',
    options:['Saving the state of an old process and loading the saved state for a new process','Switching from dark mode to light mode','Turning the monitor on and off','Changing the CPU processor physically'],
    correct:0, hint:'How the CPU juggles multiple tasks rapidly.',
    professorAsk:'What is a Context Switch?',
    correctReaction:'Saving/Loading process states! Multitasking explained! 🔄',
    wrongReaction:'Dark mode to light mode?! Get out of my sight! 😡',
    wrongComment:'Context Switching is pure overhead. The OS does no useful work while switching!' },
  { topic:'OS', difficulty:'medium',
    question:'What is Paging in OS?',
    options:['A memory management scheme that eliminates the need for contiguous allocation of physical memory','Sending a pager message to the admin','Creating web pages locally','A way to divide the hard disk physically'],
    correct:0, hint:'Breaks memory into fixed-size blocks called pages and frames.',
    professorAsk:'Explain Paging in memory management!',
    correctReaction:'Non-contiguous memory allocation! Excellent! 📄',
    wrongReaction:'Sending a pager message?! This is not a 1990s hospital! 😤',
    wrongComment:'Paging avoids external fragmentation by allocating memory in fixed-size blocks!' },
  { topic:'OS', difficulty:'hard',
    question:'What is Thrashing?',
    options:['When a system spends more time paging (swapping memory) than executing processes','When the CPU overheats and vibrates','A sorting algorithm for large arrays','Deleting files rapidly'],
    correct:0, hint:'The computer becomes extremely slow because it\'s constantly fetching data from the disk.',
    professorAsk:'What causes a system to start Thrashing?',
    correctReaction:'High page fault rate! OS performance killer! 📉',
    wrongReaction:'Overheats and vibrates?! Are you putting your laptop in a washing machine?! 😡',
    wrongComment:'Thrashing occurs when memory is overcommitted and the OS constantly swaps pages!' },
  { topic:'OS', difficulty:'medium',
    question:'What is a Semaphore?',
    options:['An integer variable used to control access to a common resource in concurrent systems','A flag used in sailing','A type of network router','A hardware interrupt signal'],
    correct:0, hint:'Invented by Dijkstra, it uses Wait(P) and Signal(V) operations.',
    professorAsk:'What is a Semaphore?',
    correctReaction:'Integer for synchronization! Concurrency genius! 🚦',
    wrongReaction:'A flag in sailing?! We are navigating code, not the ocean! 😤',
    wrongComment:'Semaphores solve the critical section problem (Mutex is a binary semaphore)!' },
  { topic:'OS', difficulty:'hard',
    question:'What is the Banker\'s Algorithm used for?',
    options:['Deadlock Avoidance','Calculating compound interest','Routing network packets','Sorting bank transactions'],
    correct:0, hint:'It checks if resource allocation will leave the system in a safe state.',
    professorAsk:'What is the Banker\'s Algorithm?',
    correctReaction:'Deadlock Avoidance! Safety sequence check! 🏦',
    wrongReaction:'Calculating compound interest?! This is OS, not an MBA class! 😡',
    wrongComment:'Banker\'s Algorithm ensures the OS never enters an unsafe state that leads to deadlock!' },
  { topic:'OS', difficulty:'easy',
    question:'What is a GUI?',
    options:['Graphical User Interface','General User Instruction','Global Unix Interface','Gigabit Upload Internet'],
    correct:0, hint:'Windows, icons, menus, pointer.',
    professorAsk:'What does GUI stand for?',
    correctReaction:'Graphical User Interface! Basic but true! 🖱️',
    wrongReaction:'Gigabit Upload Internet?! Your brain needs an upload! 😤',
    wrongComment:'GUI provides visual interaction, unlike CLI (Command Line Interface)!' },
  { topic:'OS', difficulty:'medium',
    question:'What does the "fork()" system call do in Unix?',
    options:['Creates a new child process that is a duplicate of the parent process','Eats the memory','Forks a repository on GitHub','Splits the CPU cache'],
    correct:0, hint:'It branches the execution into two identical programs.',
    professorAsk:'What does the fork() system call do?',
    correctReaction:'Creates a child process! Unix fundamentals! 🍴',
    wrongReaction:'Eats the memory?! It is not a literal eating utensil! 😡',
    wrongComment:'fork() returns 0 to the child and the child\'s PID to the parent!' },
  { topic:'OS', difficulty:'medium',
    question:'What is a PCB (Process Control Block)?',
    options:['A data structure maintained by the OS for every process (stores state, PC, registers)','Printed Circuit Board on the motherboard','Process Cancellation Button','Program Counter Byte'],
    correct:0, hint:'It holds all the information the OS needs to manage a specific process.',
    professorAsk:'What is a PCB in OS context?',
    correctReaction:'Process state data structure! Well remembered! 🗂️',
    wrongReaction:'Printed Circuit Board?! Wrong subject completely! 😤',
    wrongComment:'The PCB is saved and loaded during a context switch!' },
  { topic:'OS', difficulty:'hard',
    question:'What is an Inode in Unix/Linux?',
    options:['A data structure that stores metadata about a regular file, directory, or object','An internet node','A specialized processor core','An input method for terminals'],
    correct:0, hint:'It stores size, owner, permissions, and block locations (but not the filename).',
    professorAsk:'What is an Inode?',
    correctReaction:'File metadata structure! True Linux user! 🐧',
    wrongReaction:'Internet node?! You are just guessing words now! 😡',
    wrongComment:'Inodes contain everything about a file EXCEPT its name and actual data!' },
  { topic:'OS', difficulty:'easy',
    question:'What is Multitasking?',
    options:['The OS executing multiple tasks concurrently over a certain period of time','Studying while watching Netflix','Opening multiple browser tabs','Having multiple monitors'],
    correct:0, hint:'Time-sharing the CPU rapidly so users feel things run at once.',
    professorAsk:'Define Multitasking in OS!',
    correctReaction:'Concurrent execution! Good definition! 🤹',
    wrongReaction:'Studying while watching Netflix?! That is why you are failing! 😤',
    wrongComment:'Multitasking provides the illusion of parallelism on a single-core CPU!' },
  { topic:'OS', difficulty:'medium',
    question:'Which CPU Scheduling algorithm can suffer from Starvation?',
    options:['Priority Scheduling / Shortest Job First (SJF)','Round Robin','First Come First Serve (FCFS)','None of them'],
    correct:0, hint:'If high priority/short jobs keep arriving, the others never run.',
    professorAsk:'Which algorithm suffers from starvation?',
    correctReaction:'Priority/SJF! You understand scheduling traps! ⏳',
    wrongReaction:'Round Robin?! Round Robin gives EVERYONE a slice! 😡',
    wrongComment:'Starvation is solved by "Aging" (gradually increasing priority of waiting processes)!' },
  { topic:'OS', difficulty:'medium',
    question:'What is Spooling?',
    options:['Putting data in a buffer (like a printer queue) for a slower device to process later','Winding a cable around a spool','A way to quickly cool down the CPU','Spoofing an IP address'],
    correct:0, hint:'Simultaneous Peripheral Operations On-Line. Think of printing multiple documents.',
    professorAsk:'What is Spooling?',
    correctReaction:'Buffering for slower devices! Printer analogy is perfect! 🖨️',
    wrongReaction:'Winding a cable?! I will wind you out of this college! 😤',
    wrongComment:'Spooling prevents the CPU from waiting for slow I/O devices to finish!' },
  { topic:'OS', difficulty:'hard',
    question:'What is the Translation Lookaside Buffer (TLB)?',
    options:['A memory cache that stores recent translations of virtual to physical addresses','A buffer to translate languages','A network packet queue','A graphics rendering buffer'],
    correct:0, hint:'Speeds up Paging by remembering where pages are in physical memory.',
    professorAsk:'What is the TLB?',
    correctReaction:'Virtual to physical address cache! Hardware architecture expert! ⚡',
    wrongReaction:'Buffer to translate languages?! This is not Google Translate! 😡',
    wrongComment:'TLB hits prevent the OS from having to do expensive page table lookups in RAM!' },

  // ========== CN (Original + Expanded) ==========
  { topic:'CN', difficulty:'easy',
    question:'What does HTTP stand for?',
    options:['HyperText Transfer Protocol','High Technology Transfer Program','How To Transfer Pages','HyperText Transfer Permission'],
    correct:0, hint:'It is the foundation protocol of the World Wide Web.',
    professorAsk:'What does HTTP stand for?',
    correctReaction:'HyperText Transfer Protocol! Web foundation! 🌐',
    wrongReaction:'How To Transfer Pages?! Please Google it after this! 😡',
    wrongComment:'HTTP = HyperText Transfer Protocol! Web runs on this!' },
  { topic:'CN', difficulty:'medium',
    question:'How many layers does the OSI model have?',
    options:['7 layers from Physical to Application','5 layers total','3 layers only','It depends on the network'],
    correct:0, hint:'Please All People Seem To Need Data Processing.',
    professorAsk:'How many layers in the OSI model?',
    correctReaction:'7 layers! Physical to Application! Complete! 📡',
    wrongReaction:'5 layers?! That is TCP/IP model! Different! 😤',
    wrongComment:'OSI has 7: Physical, Data Link, Network, Transport, Session, Presentation, Application!' },
  { topic:'CN', difficulty:'medium',
    question:'What is the key difference between TCP and UDP?',
    options:['TCP is reliable with handshake, UDP is fast without guarantee','TCP is always faster than UDP','They work identically under the hood','UDP was created after TCP to improve it'],
    correct:0, hint:'One guarantees delivery, the other sacrifices reliability for speed.',
    professorAsk:'TCP vs UDP - main difference?',
    correctReaction:'Reliable vs Fast! Connection vs Connectionless! 🌐',
    wrongReaction:'Identically?! They are completely different protocols! 😡',
    wrongComment:'TCP=3-way handshake+reliable, UDP=fire and forget, faster!' },
  { topic:'CN', difficulty:'easy',
    question:'What is an IP address?',
    options:['A unique numerical identifier assigned to each device on a network','Your Internet Password','Intellectual Property address','Indian Protocol number'],
    correct:0, hint:'Every device connected to a network needs one of these.',
    professorAsk:'What is an IP address?',
    correctReaction:'Unique network identifier! Every device needs one! 📍',
    wrongReaction:'Internet Password?! Your exam marks are now passworded to ZERO! 😡',
    wrongComment:'IP = Internet Protocol address, uniquely identifies network devices!' },
  { topic:'CN', difficulty:'hard',
    question:'What is the purpose of DNS?',
    options:['Translates domain names to IP addresses','Domain Name Storage server','Distributes Network Security','Dynamic Node System'],
    correct:0, hint:'It is like a phone book for the internet.',
    professorAsk:'What does DNS do?',
    correctReaction:'Domain to IP translation! Internet phonebook! 🌐',
    wrongReaction:'Network Security?! That is a firewall! 😡',
    wrongComment:'DNS = Domain Name System, translates google.com to 142.250.x.x!' },
  { topic:'CN', difficulty:'easy',
    question:'What is a MAC address?',
    options:['A physical address hardcoded into a network interface card (NIC)','A special address for Apple computers','Media Access Control server','A router configuration protocol'],
    correct:0, hint:'It is permanent and looks like 00:1A:2B:3C:4D:5E.',
    professorAsk:'What is a MAC address?',
    correctReaction:'Physical hardware address! Perfect! 🏷️',
    wrongReaction:'Special address for Apple?! A Windows PC has a MAC address too! 😤',
    wrongComment:'MAC address operates at Layer 2 (Data Link Layer) and is globally unique!' },
  { topic:'CN', difficulty:'medium',
    question:'What does ARP (Address Resolution Protocol) do?',
    options:['Maps an IP address to a MAC address','Maps domain names to IP addresses','Checks network latency','Routes packets across the globe'],
    correct:0, hint:'Translates logical network layer addresses to physical data link addresses.',
    professorAsk:'What is the purpose of ARP?',
    correctReaction:'IP to MAC resolution! Network plumbing understood! 🔧',
    wrongReaction:'Maps domains to IP?! THAT IS DNS! 😡',
    wrongComment:'When a device knows the IP but not the MAC, it broadcasts an ARP request!' },
  { topic:'CN', difficulty:'medium',
    question:'Which port does HTTP use by default?',
    options:['Port 80','Port 443','Port 21','Port 22'],
    correct:0, hint:'The most common unencrypted web port.',
    professorAsk:'Default port for HTTP?',
    correctReaction:'Port 80! Basic web networking! 🚪',
    wrongReaction:'Port 443?! That is HTTPS! 😤',
    wrongComment:'HTTP = 80, HTTPS = 443, FTP = 21, SSH = 22!' },
  { topic:'CN', difficulty:'hard',
    question:'What is a Subnet Mask?',
    options:['A 32-bit number that masks an IP address and divides it into network and host addresses','A physical mask covering a router','A tool to hide your IP address on the dark web','A password for WiFi'],
    correct:0, hint:'e.g., 255.255.255.0',
    professorAsk:'What is a Subnet Mask used for?',
    correctReaction:'Splits network and host portions! Routing master! 🎭',
    wrongReaction:'Hides your IP on the dark web?! Stop watching hacker movies! 😡',
    wrongComment:'Subnet masking allows logical division of an IP network!' },
  { topic:'CN', difficulty:'easy',
    question:'What is a Router?',
    options:['A networking device that forwards data packets between computer networks','A tool used by carpenters','A wire that connects a PC to a switch','A software firewall'],
    correct:0, hint:'It connects different networks together, like your home to the ISP.',
    professorAsk:'What does a Router do?',
    correctReaction:'Connects networks and routes packets! Correct! 🚦',
    wrongReaction:'Tool for carpenters?! We are in IT, not the woodshop! 😤',
    wrongComment:'Routers operate at OSI Layer 3 (Network Layer) using IP addresses!' },
  { topic:'CN', difficulty:'medium',
    question:'What is the difference between IPv4 and IPv6?',
    options:['IPv4 is 32-bit, IPv6 is 128-bit providing vastly more addresses','IPv6 is just faster IPv4','IPv4 is for wired, IPv6 is for wireless','There is no real difference'],
    correct:0, hint:'We ran out of the old ones because there are too many devices now.',
    professorAsk:'IPv4 vs IPv6 - what is the main difference?',
    correctReaction:'32-bit vs 128-bit address space! Future-proof answer! 🔢',
    wrongReaction:'IPv6 is for wireless?! The protocol does not care about the cable! 😡',
    wrongComment:'IPv4 supports ~4.3 billion addresses. IPv6 supports ~340 undecillion addresses!' },
  { topic:'CN', difficulty:'hard',
    question:'What is the TCP 3-Way Handshake?',
    options:['SYN, SYN-ACK, ACK','Hello, Who is there, It is me','REQUEST, ACCEPT, DATA','CONNECT, AUTH, READY'],
    correct:0, hint:'Synchronize, Synchronize-Acknowledge, Acknowledge.',
    professorAsk:'Describe the TCP Handshake!',
    correctReaction:'SYN, SYN-ACK, ACK! Reliable connection established! 🤝',
    wrongReaction:'Hello, who is there?! This is a protocol, not a knock-knock joke! 😤',
    wrongComment:'The 3-way handshake ensures both parties are ready before data is transmitted!' },
  { topic:'CN', difficulty:'medium',
    question:'What does DHCP do?',
    options:['Dynamically assigns IP addresses to devices on a network','Downloads High Capacity Packets','A protocol to hack Wi-Fi passwords','Hosts websites securely'],
    correct:0, hint:'Dynamic Host Configuration Protocol.',
    professorAsk:'What is the function of DHCP?',
    correctReaction:'Auto-assigns IP addresses! Network admin skills! 🏷️',
    wrongReaction:'Hacks Wi-Fi passwords?! Are you trying to get arrested?! 😡',
    wrongComment:'DHCP prevents IP conflicts by managing an automated pool of addresses!' },
  { topic:'CN', difficulty:'easy',
    question:'What is Ping used for?',
    options:['To test the reachability of a host on a network and measure round-trip time','To play a sound on another computer','A game like table tennis','To boost internet speed'],
    correct:0, hint:'Uses ICMP echo request and reply messages.',
    professorAsk:'What is the ping command used for?',
    correctReaction:'Tests reachability and latency! Network diagnostic 101! 🏓',
    wrongReaction:'To play a sound?! No, that is the literal definition of a bell! 😤',
    wrongComment:'Ping uses ICMP to check if a remote device is alive and reachable!' },
  { topic:'CN', difficulty:'hard',
    question:'What is NAT (Network Address Translation)?',
    options:['Translates private, non-routable IP addresses to a public IP address','Translates websites from English to Spanish','A tool for translating code between languages','A firewall specifically for Apple routers'],
    correct:0, hint:'How all the devices in your home share a single internet connection.',
    professorAsk:'What is NAT?',
    correctReaction:'Private to Public IP translation! IPv4 savior! 🌍',
    wrongReaction:'Translates English to Spanish?! Use Google Translate for that! 😡',
    wrongComment:'NAT is why your home has one public IP but 15 local devices on 192.168.x.x!' },
  { topic:'CN', difficulty:'medium',
    question:'Which OSI layer is responsible for error detection (e.g., CRC) and framing?',
    options:['Data Link Layer (Layer 2)','Network Layer (Layer 3)','Application Layer (Layer 7)','Physical Layer (Layer 1)'],
    correct:0, hint:'The layer where Switches and MAC addresses operate.',
    professorAsk:'Which layer handles framing and CRC?',
    correctReaction:'Data Link Layer! Good OSI knowledge! 🖼️',
    wrongReaction:'Physical Layer?! Layer 1 just blasts raw bits over cables! 😤',
    wrongComment:'Layer 2 (Data Link) frames the bits and uses Cyclic Redundancy Check (CRC) for errors!' },

  // ========== Math/Theory (Original + Expanded) ==========
  { topic:'Math', difficulty:'easy',
    question:'What is the derivative of sin(x)?',
    options:['cos(x)','-cos(x)','sin(x)','tan(x)'],
    correct:0, hint:'Differentiate trigonometric functions - first one in the cycle.',
    professorAsk:'What is the derivative of sin(x)?',
    correctReaction:'cos(x)! Calculus champion! 📐',
    wrongReaction:'-cos(x)?! You mixed up differentiation with integration! 😡',
    wrongComment:'d/dx(sin x) = cos x! This was Class 12 syllabus!' },
  { topic:'Math', difficulty:'easy',
    question:'What does Big O notation primarily measure?',
    options:['The efficiency and scalability of an algorithm','A specific music note in coding','The circumference of a circle','Operational overhead of software'],
    correct:0, hint:'It describes how runtime grows as input size grows.',
    professorAsk:'What is Big O notation used for?',
    correctReaction:'Algorithm complexity analysis! Perfect understanding! 📊',
    wrongReaction:'A music note?! This is CS not the music school! 😤',
    wrongComment:'Big O = worst-case time or space complexity of an algorithm!' },
  { topic:'Math', difficulty:'medium',
    question:'What is the result of 2^10?',
    options:['1024','512','2048','1000'],
    correct:0, hint:'2 to the power of 10 - a common value in computing.',
    professorAsk:'Quick math! What is 2 to the power of 10?',
    correctReaction:'1024! Binary mathematics master! 💻',
    wrongReaction:'512?! That is 2^9! Off by one! 😡',
    wrongComment:'2^10 = 1024! Common in memory (KB, MB, GB)!' },
  { topic:'Math', difficulty:'medium',
    question:'In Boolean algebra, what is De Morgan\'s Law for NOT(A AND B)?',
    options:['(NOT A) OR (NOT B)','(NOT A) AND (NOT B)','A OR B','It equals zero'],
    correct:0, hint:'Break the line, change the sign.',
    professorAsk:'State De Morgan\'s Law for NOT(A AND B)!',
    correctReaction:'NOT A OR NOT B! Logic gates logic is strong! 🧠',
    wrongReaction:'Equals zero?! You cannot just erase variables! 😤',
    wrongComment:'De Morgan\'s Law: ¬(A ∧ B) = ¬A ∨ ¬B' },
  { topic:'Math', difficulty:'hard',
    question:'What is Bayes\' Theorem used for?',
    options:['Updating probabilities based on new evidence (conditional probability)','Calculating the area of a circle','Solving differential equations','Sorting large arrays'],
    correct:0, hint:'P(A|B) = [P(B|A) * P(A)] / P(B)',
    professorAsk:'What is Bayes\' Theorem?',
    correctReaction:'Conditional probability updates! Statistics expert! 🎲',
    wrongReaction:'Sorting arrays?! Does it look like a sorting algorithm?! 😡',
    wrongComment:'Bayes\' Theorem is foundational for Machine Learning (like Naive Bayes classifiers)!' },
  { topic:'Math', difficulty:'medium',
    question:'What is a Bipartite Graph?',
    options:['A graph whose vertices can be divided into two disjoint sets where edges only connect different sets','A graph with two parts that are identical','A graph drawn with two pens','A graph with no edges'],
    correct:0, hint:'Nodes are in group A or B. Edges only go from A to B.',
    professorAsk:'Define a Bipartite Graph!',
    correctReaction:'Two disjoint sets! Excellent discrete math! 📉',
    wrongReaction:'Drawn with two pens?! Who let you into engineering?! 😤',
    wrongComment:'A graph is bipartite if and only if it does not contain an odd cycle!' },
  { topic:'Math', difficulty:'easy',
    question:'What is 5! (5 factorial)?',
    options:['120','25','100','24'],
    correct:0, hint:'5 * 4 * 3 * 2 * 1',
    professorAsk:'Quick, what is 5 factorial?',
    correctReaction:'120! Fast mental math! 🧮',
    wrongReaction:'25?! That is 5 squared! 😡',
    wrongComment:'Factorial (n!) is used heavily in permutations and combinations!' },
  { topic:'Math', difficulty:'medium',
    question:'What is a Prime Number?',
    options:['A whole number greater than 1 whose only divisors are 1 and itself','Any odd number','A number used by Amazon Prime','Any number divisible by 2'],
    correct:0, hint:'2, 3, 5, 7, 11...',
    professorAsk:'What defines a Prime Number?',
    correctReaction:'Only divisible by 1 and itself! Cryptography basis! 🔐',
    wrongReaction:'Used by Amazon Prime?! Oh my goodness... 😤',
    wrongComment:'Prime numbers are the building blocks of RSA encryption algorithms!' },
  { topic:'Math', difficulty:'hard',
    question:'What is the determinant of a 2x2 matrix: [[a,b], [c,d]]?',
    options:['(a*d) - (b*c)','(a+b) - (c+d)','a*b*c*d','It is always zero'],
    correct:0, hint:'Cross multiply and subtract.',
    professorAsk:'Formula for a 2x2 matrix determinant?',
    correctReaction:'ad - bc! Linear algebra is strong! 📐',
    wrongReaction:'Always zero?! Then why would we calculate it?! 😡',
    wrongComment:'Determinants are used to find inverses and solve linear equations!' },
  { topic:'Math', difficulty:'easy',
    question:'What is modulo arithmetic?',
    options:['Finding the remainder after division','Calculating percentages','Solving algebraic graphs','Translating code to machine language'],
    correct:0, hint:'The % operator in programming.',
    professorAsk:'What does the modulo operator do?',
    correctReaction:'Finds the remainder! Very useful in coding! ➗',
    wrongReaction:'Calculating percentages?! Modulo is NOT percent! 😤',
    wrongComment:'10 % 3 = 1 (because 10 divided by 3 leaves a remainder of 1)!' },

  // ========== General CS (Original + Expanded) ==========
  { topic:'CS', difficulty:'easy',
    question:'What is recursion in programming?',
    options:['A function that calls itself with a base case','Repeating the same lecture twice','Going back to first principles','A loop that has no termination condition'],
    correct:0, hint:'The function calls itself - but always needs a stopping condition.',
    professorAsk:'Define recursion!',
    correctReaction:'Function calls itself with a base case! 🔄',
    wrongReaction:'Repeating lectures?! Like I am forced to do now?! 😡',
    wrongComment:'To understand recursion, you must first understand recursion!' },
  { topic:'CS', difficulty:'easy',
    question:'What does a compiler do?',
    options:['Translates entire source code to machine code before execution','Automatically fixes all your code errors','Executes code one line at a time','A special type of processor chip'],
    correct:0, hint:'It converts the whole program at once, not line by line.',
    professorAsk:'What does a compiler do?',
    correctReaction:'Translates entire source to machine code! Correct! ⚙️',
    wrongReaction:'Fixes errors automatically?! I WISH it could fix yours! 😤',
    wrongComment:'Compiler=whole program translation. Interpreter=line by line!' },
  { topic:'CS', difficulty:'easy',
    question:'What is the fundamental difference between RAM and ROM?',
    options:['RAM is volatile (loses data), ROM is non-volatile (permanent)','RAM is always slower than ROM','RAM is read-only, ROM is writable','There is absolutely no difference'],
    correct:0, hint:'What happens to RAM data when you turn off the power?',
    professorAsk:'RAM vs ROM - fundamental difference?',
    correctReaction:'Volatile vs Non-volatile storage! Hardware expert! 💡',
    wrongReaction:'No difference?! 70 years of computing history disagrees! 😡',
    wrongComment:'RAM = loses data on power off. ROM = permanently stores data!' },
  { topic:'CS', difficulty:'easy',
    question:'What is an API?',
    options:['Application Programming Interface - allows software to communicate','A secret Programming Ingredient','Automated Program Input system','Annual Programming Index report'],
    correct:0, hint:'It defines how software components should interact with each other.',
    professorAsk:'What is an API?',
    correctReaction:'Interface between software components! Modern dev essential! 🔌',
    wrongReaction:'A secret ingredient?! We are building software not biryani! 😤',
    wrongComment:'API = contract/interface that allows applications to talk to each other!' },
  { topic:'CS', difficulty:'easy',
    question:'What is Git primarily used for?',
    options:['Version control - tracking changes in source code over time','Downloading files from the internet quickly','It is a programming language like Python','It is just an alternative to GitHub'],
    correct:0, hint:'It helps teams collaborate on code without overwriting each other.',
    professorAsk:'What is Git used for?',
    correctReaction:'Version control! Every professional developer uses Git! 📝',
    wrongReaction:'Downloading files?! That is a browser or wget! 😡',
    wrongComment:'Git tracks code history and enables team collaboration!' },
  { topic:'CS', difficulty:'easy',
    question:'What does CPU stand for?',
    options:['Central Processing Unit','Computer Personal Unit','Core Processing Utility chip','Central Program Updater'],
    correct:0, hint:'It is the brain of the computer that executes instructions.',
    professorAsk:'What does CPU stand for?',
    correctReaction:'Central Processing Unit! Brain of the computer! 🧠',
    wrongReaction:'Computer Personal Unit?! WHO taught you this?! Show me their name! 😤',
    wrongComment:'CPU = Central Processing Unit! The brain that executes all instructions!' },
  { topic:'CS', difficulty:'medium',
    question:'What is a boolean data type?',
    options:['A data type that can only be true or false','A special type of integer number','Used for storing text data only','Represents complex imaginary numbers'],
    correct:0, hint:'Named after mathematician George Boole, only two possible values.',
    professorAsk:'What is a boolean data type?',
    correctReaction:'True or False only! Boolean logic master! 💡',
    wrongReaction:'A special integer?! Boolean is NOT an integer! 😤',
    wrongComment:'Boolean = only true/false! Named after George Boole!' },
  { topic:'CS', difficulty:'medium',
    question:'What is the primary purpose of a firewall?',
    options:['Monitor and control incoming and outgoing network traffic','Prevent the computer from overheating physically','Speed up the internet connection','Securely store user passwords'],
    correct:0, hint:'It is a network security barrier.',
    professorAsk:'What does a firewall do?',
    correctReaction:'Network security and traffic control! 🔥🧱',
    wrongReaction:'Prevent overheating?! That is literally a FAN and heatsink! 😡',
    wrongComment:'Firewall = network security barrier, filters traffic by rules!' },
  { topic:'CS', difficulty:'easy',
    question:'What is cloud computing?',
    options:['Delivering computing services like servers and storage over the internet','Doing calculations while looking at clouds outside','Software specifically for weather prediction','Computing done wirelessly without any cables'],
    correct:0, hint:'Think of using someone else\'s powerful computers via the internet.',
    professorAsk:'Define cloud computing!',
    correctReaction:'On-demand computing services over internet! ☁️',
    wrongReaction:'Calculations while looking at clouds?! HEAD IN THE BOOKS! 😤',
    wrongComment:'Cloud = remote servers for compute, storage, and services over internet!' },
  { topic:'CS', difficulty:'hard',
    question:'What is the difference between symmetric and asymmetric encryption?',
    options:['Symmetric uses one key for both, asymmetric uses public/private key pair','Symmetric is always more secure','Asymmetric uses the same key for both operations','There is no practical difference between them'],
    correct:0, hint:'Think about how many keys are involved in each type.',
    professorAsk:'Symmetric vs Asymmetric encryption?',
    correctReaction:'One key vs Key pair! Security expert! 🔐',
    wrongReaction:'No practical difference?! Then why use both?! 😡',
    wrongComment:'Symmetric=1 shared key (AES), Asymmetric=public+private pair (RSA)!' },
  { topic:'CS', difficulty:'hard',
    question:'What is the CAP theorem in distributed systems?',
    options:['You can only guarantee 2 of: Consistency, Availability, Partition tolerance','CAP stands for Computer Automated Processing','All three properties can always be achieved','Only applies to databases not distributed systems'],
    correct:0, hint:'In distributed systems, there is always a trade-off.',
    professorAsk:'What is the CAP theorem?',
    correctReaction:'Pick only 2 of C, A, P! Distributed systems master! 🌐',
    wrongReaction:'Computer Automated Processing?! That is not even a thing! 😡',
    wrongComment:'CAP: Consistency + Availability + Partition Tolerance - pick any 2!' },
  { topic:'CS', difficulty:'medium',
    question:'What is the difference between HTTP and HTTPS?',
    options:['HTTPS adds SSL/TLS encryption for secure communication','HTTPS is always slower than HTTP','There is no real difference between them','HTTPS only works on mobile devices'],
    correct:0, hint:'The S stands for something related to security.',
    professorAsk:'HTTP vs HTTPS - what is the difference?',
    correctReaction:'SSL/TLS encryption! Security-conscious student! 🔒',
    wrongReaction:'No real difference?! Banks would disagree! 😡',
    wrongComment:'HTTPS = HTTP + SSL/TLS encryption! The S = Secure!' },
  { topic:'CS', difficulty:'medium',
    question:'What does an IDE stand for?',
    options:['Integrated Development Environment','Internet Development Engine','Intelligent Debugging Extension','Internal Data Executor'],
    correct:0, hint:'It is a software application that provides tools for writing code.',
    professorAsk:'What does IDE stand for?',
    correctReaction:'Integrated Development Environment! Code tools expert! 💻',
    wrongReaction:'Internet Development Engine?! This is not the web! 😤',
    wrongComment:'IDE = Integrated Development Environment (VS Code, IntelliJ, Eclipse)!' },
  { topic:'CS', difficulty:'easy',
    question:'What is a bug in programming?',
    options:['An error or flaw in the program that causes incorrect behavior','A literal insect that entered the computer hardware','A feature that was added without documentation','A virus that attacks the computer'],
    correct:0, hint:'Named after an actual insect found in early computers!',
    professorAsk:'What is a programming bug?',
    correctReaction:'An error causing incorrect behavior! History lesson too! 🐛',
    wrongReaction:'A literal insect?! Check your computer then! 😤',
    wrongComment:'Bug = error in code! Term from Grace Hopper finding actual moth in 1947!' },
  { topic:'CS', difficulty:'medium',
    question:'What is machine learning in simple terms?',
    options:['Computers learning patterns from data to make predictions without explicit programming','Teaching machines to speak human languages','A type of computer hardware upgrade','Programming robots to walk and move'],
    correct:0, hint:'It learns from examples rather than following fixed rules.',
    professorAsk:'Define machine learning!',
    correctReaction:'Learning from data patterns! AI awareness! 🤖',
    wrongReaction:'Teaching machines to speak?! That is NLP, different thing! 😡',
    wrongComment:'ML = algorithms that improve through experience/data without explicit rules!' },
  { topic:'CS', difficulty:'hard',
    question:'What is Big O notation O(1)?',
    options:['Constant time - execution time does not depend on input size','The algorithm takes one second always','The slowest possible algorithm','Only works for single element inputs'],
    correct:0, hint:'No matter how large the input is, time stays the same.',
    professorAsk:'What does O(1) mean in Big O notation?',
    correctReaction:'Constant time! Input size does not matter! Perfect! ⚡',
    wrongReaction:'Takes one second?! O(1) is about scaling not duration! 😡',
    wrongComment:'O(1) = constant time, always same speed regardless of input size!' },
  { topic:'CS', difficulty:'medium',
    question:'What is a REST API?',
    options:['Representational State Transfer - architectural style using standard HTTP methods','A sleep mode for servers','A database query language','An operating system for routers'],
    correct:0, hint:'It uses GET, POST, PUT, DELETE.',
    professorAsk:'What is a REST API?',
    correctReaction:'Architectural style for web services! Great job! 🌐',
    wrongReaction:'A sleep mode?! Are you the one sleeping right now?! 😤',
    wrongComment:'REST relies on stateless, client-server architecture using HTTP!' },
  { topic:'CS', difficulty:'medium',
    question:'What is Docker used for?',
    options:['Containerizing applications with their dependencies to run uniformly anywhere','Docking a laptop to a monitor','Storing physical hard drives','Downloading torrents securely'],
    correct:0, hint:'Build once, run anywhere in a lightweight isolated environment.',
    professorAsk:'What is Docker?',
    correctReaction:'Containerization tool! DevOps knowledge! 🐳',
    wrongReaction:'Docking a laptop?! This is software engineering, not office setup! 😡',
    wrongComment:'Docker packages apps into containers, which share the host OS kernel!' },
  { topic:'CS', difficulty:'hard',
    question:'What is a Microservices Architecture?',
    options:['Breaking down an application into small, independent, loosely coupled services','Creating very small computer chips','A startup business model','A database design pattern'],
    correct:0, hint:'Opposite of a Monolithic architecture.',
    professorAsk:'Explain Microservices!',
    correctReaction:'Small independent services! Modern system design! 🏗️',
    wrongReaction:'Creating small chips?! That is nanotechnology! 😤',
    wrongComment:'Microservices allow teams to deploy, scale, and update parts of an app independently!' },
  { topic:'CS', difficulty:'easy',
    question:'What is Phishing in cybersecurity?',
    options:['Fraudulent attempt to obtain sensitive information by disguising as a trustworthy entity','Catching fish online','A type of encryption','Scanning a network for open ports'],
    correct:0, hint:'Like an email pretending to be from your bank.',
    professorAsk:'What is a Phishing attack?',
    correctReaction:'Social engineering to steal data! Stay safe! 🎣',
    wrongReaction:'Catching fish online?! Are you playing Animal Crossing?! 😡',
    wrongComment:'Phishing relies on human error rather than technical exploits!' }
];

/* ============================================================
   Shuffle and Randomize Answer Positions
   ============================================================ */
function randomizeAnswers(q) {
  const opts = q.options.map((text, i) => ({ text, isCorrect: i === q.correct }));
  // Fisher-Yates shuffle
  for (let i = opts.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [opts[i], opts[j]] = [opts[j], opts[i]];
  }
  const newCorrect = opts.findIndex(o => o.isCorrect);
  return { ...q, options: opts.map(o => o.text), correct: newCorrect };
}

function shuffleAndPick(arr, count) {
  const shuffled = [...arr].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count).map(q => randomizeAnswers(q));
}
